// Code generated by ent, DO NOT EDIT.

package schedulingaction

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the schedulingaction type in the database.
	Label = "scheduling_action"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPolicyID holds the string denoting the policy_id field in the database.
	FieldPolicyID = "policy_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldMonitorID holds the string denoting the monitor_id field in the database.
	FieldMonitorID = "monitor_id"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldOriginalPriority holds the string denoting the original_priority field in the database.
	FieldOriginalPriority = "original_priority"
	// FieldRestored holds the string denoting the restored field in the database.
	FieldRestored = "restored"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the schedulingaction in the database.
	Table = "scheduling_actions"
)

// Columns holds all SQL columns for schedulingaction fields.
var Columns = []string{
	FieldID,
	FieldPolicyID,
	FieldAccountID,
	FieldMonitorID,
	FieldAction,
	FieldReason,
	FieldOriginalPriority,
	FieldRestored,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ActionValidator is a validator for the "action" field. It is called by the builders before save.
	ActionValidator func(string) error
	// DefaultReason holds the default value on creation for the "reason" field.
	DefaultReason string
	// ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	ReasonValidator func(string) error
	// DefaultOriginalPriority holds the default value on creation for the "original_priority" field.
	DefaultOriginalPriority int
	// DefaultRestored holds the default value on creation for the "restored" field.
	DefaultRestored bool
)

// OrderOption defines the ordering options for the SchedulingAction queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPolicyID orders the results by the policy_id field.
func ByPolicyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPolicyID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByMonitorID orders the results by the monitor_id field.
func ByMonitorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonitorID, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByOriginalPriority orders the results by the original_priority field.
func ByOriginalPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginalPriority, opts...).ToFunc()
}

// ByRestored orders the results by the restored field.
func ByRestored(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRestored, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
