// Code generated by ent, DO NOT EDIT.

package schedulingaction

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldLTE(FieldID, id))
}

// PolicyID applies equality check predicate on the "policy_id" field. It's identical to PolicyIDEQ.
func PolicyID(v int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldEQ(FieldPolicyID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldEQ(FieldAccountID, v))
}

// MonitorID applies equality check predicate on the "monitor_id" field. It's identical to MonitorIDEQ.
func MonitorID(v int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldEQ(FieldMonitorID, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldEQ(FieldAction, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldEQ(FieldReason, v))
}

// OriginalPriority applies equality check predicate on the "original_priority" field. It's identical to OriginalPriorityEQ.
func OriginalPriority(v int) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldEQ(FieldOriginalPriority, v))
}

// Restored applies equality check predicate on the "restored" field. It's identical to RestoredEQ.
func Restored(v bool) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldEQ(FieldRestored, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldEQ(FieldCreatedAt, v))
}

// PolicyIDEQ applies the EQ predicate on the "policy_id" field.
func PolicyIDEQ(v int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldEQ(FieldPolicyID, v))
}

// PolicyIDNEQ applies the NEQ predicate on the "policy_id" field.
func PolicyIDNEQ(v int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldNEQ(FieldPolicyID, v))
}

// PolicyIDIn applies the In predicate on the "policy_id" field.
func PolicyIDIn(vs ...int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldIn(FieldPolicyID, vs...))
}

// PolicyIDNotIn applies the NotIn predicate on the "policy_id" field.
func PolicyIDNotIn(vs ...int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldNotIn(FieldPolicyID, vs...))
}

// PolicyIDGT applies the GT predicate on the "policy_id" field.
func PolicyIDGT(v int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldGT(FieldPolicyID, v))
}

// PolicyIDGTE applies the GTE predicate on the "policy_id" field.
func PolicyIDGTE(v int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldGTE(FieldPolicyID, v))
}

// PolicyIDLT applies the LT predicate on the "policy_id" field.
func PolicyIDLT(v int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldLT(FieldPolicyID, v))
}

// PolicyIDLTE applies the LTE predicate on the "policy_id" field.
func PolicyIDLTE(v int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldLTE(FieldPolicyID, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldLTE(FieldAccountID, v))
}

// MonitorIDEQ applies the EQ predicate on the "monitor_id" field.
func MonitorIDEQ(v int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldEQ(FieldMonitorID, v))
}

// MonitorIDNEQ applies the NEQ predicate on the "monitor_id" field.
func MonitorIDNEQ(v int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldNEQ(FieldMonitorID, v))
}

// MonitorIDIn applies the In predicate on the "monitor_id" field.
func MonitorIDIn(vs ...int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldIn(FieldMonitorID, vs...))
}

// MonitorIDNotIn applies the NotIn predicate on the "monitor_id" field.
func MonitorIDNotIn(vs ...int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldNotIn(FieldMonitorID, vs...))
}

// MonitorIDGT applies the GT predicate on the "monitor_id" field.
func MonitorIDGT(v int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldGT(FieldMonitorID, v))
}

// MonitorIDGTE applies the GTE predicate on the "monitor_id" field.
func MonitorIDGTE(v int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldGTE(FieldMonitorID, v))
}

// MonitorIDLT applies the LT predicate on the "monitor_id" field.
func MonitorIDLT(v int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldLT(FieldMonitorID, v))
}

// MonitorIDLTE applies the LTE predicate on the "monitor_id" field.
func MonitorIDLTE(v int64) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldLTE(FieldMonitorID, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldContainsFold(FieldAction, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldContainsFold(FieldReason, v))
}

// OriginalPriorityEQ applies the EQ predicate on the "original_priority" field.
func OriginalPriorityEQ(v int) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldEQ(FieldOriginalPriority, v))
}

// OriginalPriorityNEQ applies the NEQ predicate on the "original_priority" field.
func OriginalPriorityNEQ(v int) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldNEQ(FieldOriginalPriority, v))
}

// OriginalPriorityIn applies the In predicate on the "original_priority" field.
func OriginalPriorityIn(vs ...int) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldIn(FieldOriginalPriority, vs...))
}

// OriginalPriorityNotIn applies the NotIn predicate on the "original_priority" field.
func OriginalPriorityNotIn(vs ...int) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldNotIn(FieldOriginalPriority, vs...))
}

// OriginalPriorityGT applies the GT predicate on the "original_priority" field.
func OriginalPriorityGT(v int) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldGT(FieldOriginalPriority, v))
}

// OriginalPriorityGTE applies the GTE predicate on the "original_priority" field.
func OriginalPriorityGTE(v int) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldGTE(FieldOriginalPriority, v))
}

// OriginalPriorityLT applies the LT predicate on the "original_priority" field.
func OriginalPriorityLT(v int) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldLT(FieldOriginalPriority, v))
}

// OriginalPriorityLTE applies the LTE predicate on the "original_priority" field.
func OriginalPriorityLTE(v int) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldLTE(FieldOriginalPriority, v))
}

// RestoredEQ applies the EQ predicate on the "restored" field.
func RestoredEQ(v bool) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldEQ(FieldRestored, v))
}

// RestoredNEQ applies the NEQ predicate on the "restored" field.
func RestoredNEQ(v bool) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldNEQ(FieldRestored, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SchedulingAction) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SchedulingAction) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SchedulingAction) predicate.SchedulingAction {
	return predicate.SchedulingAction(sql.NotPredicates(p))
}
