// Code generated by ent, DO NOT EDIT.

package schedulingpolicy

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the schedulingpolicy type in the database.
	Label = "scheduling_policy"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldMonitorID holds the string denoting the monitor_id field in the database.
	FieldMonitorID = "monitor_id"
	// FieldAccountIds holds the string denoting the account_ids field in the database.
	FieldAccountIds = "account_ids"
	// FieldTriggerConsecutiveFailures holds the string denoting the trigger_consecutive_failures field in the database.
	FieldTriggerConsecutiveFailures = "trigger_consecutive_failures"
	// FieldTriggerLatencyMs holds the string denoting the trigger_latency_ms field in the database.
	FieldTriggerLatencyMs = "trigger_latency_ms"
	// FieldActionType holds the string denoting the action_type field in the database.
	FieldActionType = "action_type"
	// FieldPauseMinutes holds the string denoting the pause_minutes field in the database.
	FieldPauseMinutes = "pause_minutes"
	// FieldPriorityDelta holds the string denoting the priority_delta field in the database.
	FieldPriorityDelta = "priority_delta"
	// FieldRecoverConsecutiveSuccesses holds the string denoting the recover_consecutive_successes field in the database.
	FieldRecoverConsecutiveSuccesses = "recover_consecutive_successes"
	// FieldCooldownMinutes holds the string denoting the cooldown_minutes field in the database.
	FieldCooldownMinutes = "cooldown_minutes"
	// Table holds the table name of the schedulingpolicy in the database.
	Table = "scheduling_policies"
)

// Columns holds all SQL columns for schedulingpolicy fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldEnabled,
	FieldMonitorID,
	FieldAccountIds,
	FieldTriggerConsecutiveFailures,
	FieldTriggerLatencyMs,
	FieldActionType,
	FieldPauseMinutes,
	FieldPriorityDelta,
	FieldRecoverConsecutiveSuccesses,
	FieldCooldownMinutes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultAccountIds holds the default value on creation for the "account_ids" field.
	DefaultAccountIds []int64
	// DefaultTriggerConsecutiveFailures holds the default value on creation for the "trigger_consecutive_failures" field.
	DefaultTriggerConsecutiveFailures int
	// TriggerConsecutiveFailuresValidator is a validator for the "trigger_consecutive_failures" field. It is called by the builders before save.
	TriggerConsecutiveFailuresValidator func(int) error
	// DefaultTriggerLatencyMs holds the default value on creation for the "trigger_latency_ms" field.
	DefaultTriggerLatencyMs int
	// TriggerLatencyMsValidator is a validator for the "trigger_latency_ms" field. It is called by the builders before save.
	TriggerLatencyMsValidator func(int) error
	// DefaultActionType holds the default value on creation for the "action_type" field.
	DefaultActionType string
	// ActionTypeValidator is a validator for the "action_type" field. It is called by the builders before save.
	ActionTypeValidator func(string) error
	// DefaultPauseMinutes holds the default value on creation for the "pause_minutes" field.
	DefaultPauseMinutes int
	// PauseMinutesValidator is a validator for the "pause_minutes" field. It is called by the builders before save.
	PauseMinutesValidator func(int) error
	// DefaultPriorityDelta holds the default value on creation for the "priority_delta" field.
	DefaultPriorityDelta int
	// PriorityDeltaValidator is a validator for the "priority_delta" field. It is called by the builders before save.
	PriorityDeltaValidator func(int) error
	// DefaultRecoverConsecutiveSuccesses holds the default value on creation for the "recover_consecutive_successes" field.
	DefaultRecoverConsecutiveSuccesses int
	// RecoverConsecutiveSuccessesValidator is a validator for the "recover_consecutive_successes" field. It is called by the builders before save.
	RecoverConsecutiveSuccessesValidator func(int) error
	// DefaultCooldownMinutes holds the default value on creation for the "cooldown_minutes" field.
	DefaultCooldownMinutes int
	// CooldownMinutesValidator is a validator for the "cooldown_minutes" field. It is called by the builders before save.
	CooldownMinutesValidator func(int) error
)

// OrderOption defines the ordering options for the SchedulingPolicy queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByMonitorID orders the results by the monitor_id field.
func ByMonitorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonitorID, opts...).ToFunc()
}

// ByTriggerConsecutiveFailures orders the results by the trigger_consecutive_failures field.
func ByTriggerConsecutiveFailures(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggerConsecutiveFailures, opts...).ToFunc()
}

// ByTriggerLatencyMs orders the results by the trigger_latency_ms field.
func ByTriggerLatencyMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggerLatencyMs, opts...).ToFunc()
}

// ByActionType orders the results by the action_type field.
func ByActionType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActionType, opts...).ToFunc()
}

// ByPauseMinutes orders the results by the pause_minutes field.
func ByPauseMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPauseMinutes, opts...).ToFunc()
}

// ByPriorityDelta orders the results by the priority_delta field.
func ByPriorityDelta(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriorityDelta, opts...).ToFunc()
}

// ByRecoverConsecutiveSuccesses orders the results by the recover_consecutive_successes field.
func ByRecoverConsecutiveSuccesses(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecoverConsecutiveSuccesses, opts...).ToFunc()
}

// ByCooldownMinutes orders the results by the cooldown_minutes field.
func ByCooldownMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCooldownMinutes, opts...).ToFunc()
}
