// Code generated by ent, DO NOT EDIT.

package schedulingpolicy

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldEQ(FieldName, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldEQ(FieldEnabled, v))
}

// MonitorID applies equality check predicate on the "monitor_id" field. It's identical to MonitorIDEQ.
func MonitorID(v int64) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldEQ(FieldMonitorID, v))
}

// TriggerConsecutiveFailures applies equality check predicate on the "trigger_consecutive_failures" field. It's identical to TriggerConsecutiveFailuresEQ.
func TriggerConsecutiveFailures(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldEQ(FieldTriggerConsecutiveFailures, v))
}

// TriggerLatencyMs applies equality check predicate on the "trigger_latency_ms" field. It's identical to TriggerLatencyMsEQ.
func TriggerLatencyMs(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldEQ(FieldTriggerLatencyMs, v))
}

// ActionType applies equality check predicate on the "action_type" field. It's identical to ActionTypeEQ.
func ActionType(v string) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldEQ(FieldActionType, v))
}

// PauseMinutes applies equality check predicate on the "pause_minutes" field. It's identical to PauseMinutesEQ.
func PauseMinutes(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldEQ(FieldPauseMinutes, v))
}

// PriorityDelta applies equality check predicate on the "priority_delta" field. It's identical to PriorityDeltaEQ.
func PriorityDelta(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldEQ(FieldPriorityDelta, v))
}

// RecoverConsecutiveSuccesses applies equality check predicate on the "recover_consecutive_successes" field. It's identical to RecoverConsecutiveSuccessesEQ.
func RecoverConsecutiveSuccesses(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldEQ(FieldRecoverConsecutiveSuccesses, v))
}

// CooldownMinutes applies equality check predicate on the "cooldown_minutes" field. It's identical to CooldownMinutesEQ.
func CooldownMinutes(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldEQ(FieldCooldownMinutes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldContainsFold(FieldName, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldNEQ(FieldEnabled, v))
}

// MonitorIDEQ applies the EQ predicate on the "monitor_id" field.
func MonitorIDEQ(v int64) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldEQ(FieldMonitorID, v))
}

// MonitorIDNEQ applies the NEQ predicate on the "monitor_id" field.
func MonitorIDNEQ(v int64) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldNEQ(FieldMonitorID, v))
}

// MonitorIDIn applies the In predicate on the "monitor_id" field.
func MonitorIDIn(vs ...int64) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldIn(FieldMonitorID, vs...))
}

// MonitorIDNotIn applies the NotIn predicate on the "monitor_id" field.
func MonitorIDNotIn(vs ...int64) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldNotIn(FieldMonitorID, vs...))
}

// MonitorIDGT applies the GT predicate on the "monitor_id" field.
func MonitorIDGT(v int64) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldGT(FieldMonitorID, v))
}

// MonitorIDGTE applies the GTE predicate on the "monitor_id" field.
func MonitorIDGTE(v int64) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldGTE(FieldMonitorID, v))
}

// MonitorIDLT applies the LT predicate on the "monitor_id" field.
func MonitorIDLT(v int64) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldLT(FieldMonitorID, v))
}

// MonitorIDLTE applies the LTE predicate on the "monitor_id" field.
func MonitorIDLTE(v int64) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldLTE(FieldMonitorID, v))
}

// TriggerConsecutiveFailuresEQ applies the EQ predicate on the "trigger_consecutive_failures" field.
func TriggerConsecutiveFailuresEQ(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldEQ(FieldTriggerConsecutiveFailures, v))
}

// TriggerConsecutiveFailuresNEQ applies the NEQ predicate on the "trigger_consecutive_failures" field.
func TriggerConsecutiveFailuresNEQ(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldNEQ(FieldTriggerConsecutiveFailures, v))
}

// TriggerConsecutiveFailuresIn applies the In predicate on the "trigger_consecutive_failures" field.
func TriggerConsecutiveFailuresIn(vs ...int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldIn(FieldTriggerConsecutiveFailures, vs...))
}

// TriggerConsecutiveFailuresNotIn applies the NotIn predicate on the "trigger_consecutive_failures" field.
func TriggerConsecutiveFailuresNotIn(vs ...int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldNotIn(FieldTriggerConsecutiveFailures, vs...))
}

// TriggerConsecutiveFailuresGT applies the GT predicate on the "trigger_consecutive_failures" field.
func TriggerConsecutiveFailuresGT(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldGT(FieldTriggerConsecutiveFailures, v))
}

// TriggerConsecutiveFailuresGTE applies the GTE predicate on the "trigger_consecutive_failures" field.
func TriggerConsecutiveFailuresGTE(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldGTE(FieldTriggerConsecutiveFailures, v))
}

// TriggerConsecutiveFailuresLT applies the LT predicate on the "trigger_consecutive_failures" field.
func TriggerConsecutiveFailuresLT(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldLT(FieldTriggerConsecutiveFailures, v))
}

// TriggerConsecutiveFailuresLTE applies the LTE predicate on the "trigger_consecutive_failures" field.
func TriggerConsecutiveFailuresLTE(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldLTE(FieldTriggerConsecutiveFailures, v))
}

// TriggerLatencyMsEQ applies the EQ predicate on the "trigger_latency_ms" field.
func TriggerLatencyMsEQ(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldEQ(FieldTriggerLatencyMs, v))
}

// TriggerLatencyMsNEQ applies the NEQ predicate on the "trigger_latency_ms" field.
func TriggerLatencyMsNEQ(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldNEQ(FieldTriggerLatencyMs, v))
}

// TriggerLatencyMsIn applies the In predicate on the "trigger_latency_ms" field.
func TriggerLatencyMsIn(vs ...int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldIn(FieldTriggerLatencyMs, vs...))
}

// TriggerLatencyMsNotIn applies the NotIn predicate on the "trigger_latency_ms" field.
func TriggerLatencyMsNotIn(vs ...int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldNotIn(FieldTriggerLatencyMs, vs...))
}

// TriggerLatencyMsGT applies the GT predicate on the "trigger_latency_ms" field.
func TriggerLatencyMsGT(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldGT(FieldTriggerLatencyMs, v))
}

// TriggerLatencyMsGTE applies the GTE predicate on the "trigger_latency_ms" field.
func TriggerLatencyMsGTE(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldGTE(FieldTriggerLatencyMs, v))
}

// TriggerLatencyMsLT applies the LT predicate on the "trigger_latency_ms" field.
func TriggerLatencyMsLT(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldLT(FieldTriggerLatencyMs, v))
}

// TriggerLatencyMsLTE applies the LTE predicate on the "trigger_latency_ms" field.
func TriggerLatencyMsLTE(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldLTE(FieldTriggerLatencyMs, v))
}

// ActionTypeEQ applies the EQ predicate on the "action_type" field.
func ActionTypeEQ(v string) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldEQ(FieldActionType, v))
}

// ActionTypeNEQ applies the NEQ predicate on the "action_type" field.
func ActionTypeNEQ(v string) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldNEQ(FieldActionType, v))
}

// ActionTypeIn applies the In predicate on the "action_type" field.
func ActionTypeIn(vs ...string) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldIn(FieldActionType, vs...))
}

// ActionTypeNotIn applies the NotIn predicate on the "action_type" field.
func ActionTypeNotIn(vs ...string) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldNotIn(FieldActionType, vs...))
}

// ActionTypeGT applies the GT predicate on the "action_type" field.
func ActionTypeGT(v string) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldGT(FieldActionType, v))
}

// ActionTypeGTE applies the GTE predicate on the "action_type" field.
func ActionTypeGTE(v string) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldGTE(FieldActionType, v))
}

// ActionTypeLT applies the LT predicate on the "action_type" field.
func ActionTypeLT(v string) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldLT(FieldActionType, v))
}

// ActionTypeLTE applies the LTE predicate on the "action_type" field.
func ActionTypeLTE(v string) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldLTE(FieldActionType, v))
}

// ActionTypeContains applies the Contains predicate on the "action_type" field.
func ActionTypeContains(v string) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldContains(FieldActionType, v))
}

// ActionTypeHasPrefix applies the HasPrefix predicate on the "action_type" field.
func ActionTypeHasPrefix(v string) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldHasPrefix(FieldActionType, v))
}

// ActionTypeHasSuffix applies the HasSuffix predicate on the "action_type" field.
func ActionTypeHasSuffix(v string) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldHasSuffix(FieldActionType, v))
}

// ActionTypeEqualFold applies the EqualFold predicate on the "action_type" field.
func ActionTypeEqualFold(v string) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldEqualFold(FieldActionType, v))
}

// ActionTypeContainsFold applies the ContainsFold predicate on the "action_type" field.
func ActionTypeContainsFold(v string) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldContainsFold(FieldActionType, v))
}

// PauseMinutesEQ applies the EQ predicate on the "pause_minutes" field.
func PauseMinutesEQ(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldEQ(FieldPauseMinutes, v))
}

// PauseMinutesNEQ applies the NEQ predicate on the "pause_minutes" field.
func PauseMinutesNEQ(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldNEQ(FieldPauseMinutes, v))
}

// PauseMinutesIn applies the In predicate on the "pause_minutes" field.
func PauseMinutesIn(vs ...int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldIn(FieldPauseMinutes, vs...))
}

// PauseMinutesNotIn applies the NotIn predicate on the "pause_minutes" field.
func PauseMinutesNotIn(vs ...int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldNotIn(FieldPauseMinutes, vs...))
}

// PauseMinutesGT applies the GT predicate on the "pause_minutes" field.
func PauseMinutesGT(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldGT(FieldPauseMinutes, v))
}

// PauseMinutesGTE applies the GTE predicate on the "pause_minutes" field.
func PauseMinutesGTE(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldGTE(FieldPauseMinutes, v))
}

// PauseMinutesLT applies the LT predicate on the "pause_minutes" field.
func PauseMinutesLT(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldLT(FieldPauseMinutes, v))
}

// PauseMinutesLTE applies the LTE predicate on the "pause_minutes" field.
func PauseMinutesLTE(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldLTE(FieldPauseMinutes, v))
}

// PriorityDeltaEQ applies the EQ predicate on the "priority_delta" field.
func PriorityDeltaEQ(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldEQ(FieldPriorityDelta, v))
}

// PriorityDeltaNEQ applies the NEQ predicate on the "priority_delta" field.
func PriorityDeltaNEQ(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldNEQ(FieldPriorityDelta, v))
}

// PriorityDeltaIn applies the In predicate on the "priority_delta" field.
func PriorityDeltaIn(vs ...int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldIn(FieldPriorityDelta, vs...))
}

// PriorityDeltaNotIn applies the NotIn predicate on the "priority_delta" field.
func PriorityDeltaNotIn(vs ...int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldNotIn(FieldPriorityDelta, vs...))
}

// PriorityDeltaGT applies the GT predicate on the "priority_delta" field.
func PriorityDeltaGT(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldGT(FieldPriorityDelta, v))
}

// PriorityDeltaGTE applies the GTE predicate on the "priority_delta" field.
func PriorityDeltaGTE(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldGTE(FieldPriorityDelta, v))
}

// PriorityDeltaLT applies the LT predicate on the "priority_delta" field.
func PriorityDeltaLT(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldLT(FieldPriorityDelta, v))
}

// PriorityDeltaLTE applies the LTE predicate on the "priority_delta" field.
func PriorityDeltaLTE(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldLTE(FieldPriorityDelta, v))
}

// RecoverConsecutiveSuccessesEQ applies the EQ predicate on the "recover_consecutive_successes" field.
func RecoverConsecutiveSuccessesEQ(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldEQ(FieldRecoverConsecutiveSuccesses, v))
}

// RecoverConsecutiveSuccessesNEQ applies the NEQ predicate on the "recover_consecutive_successes" field.
func RecoverConsecutiveSuccessesNEQ(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldNEQ(FieldRecoverConsecutiveSuccesses, v))
}

// RecoverConsecutiveSuccessesIn applies the In predicate on the "recover_consecutive_successes" field.
func RecoverConsecutiveSuccessesIn(vs ...int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldIn(FieldRecoverConsecutiveSuccesses, vs...))
}

// RecoverConsecutiveSuccessesNotIn applies the NotIn predicate on the "recover_consecutive_successes" field.
func RecoverConsecutiveSuccessesNotIn(vs ...int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldNotIn(FieldRecoverConsecutiveSuccesses, vs...))
}

// RecoverConsecutiveSuccessesGT applies the GT predicate on the "recover_consecutive_successes" field.
func RecoverConsecutiveSuccessesGT(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldGT(FieldRecoverConsecutiveSuccesses, v))
}

// RecoverConsecutiveSuccessesGTE applies the GTE predicate on the "recover_consecutive_successes" field.
func RecoverConsecutiveSuccessesGTE(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldGTE(FieldRecoverConsecutiveSuccesses, v))
}

// RecoverConsecutiveSuccessesLT applies the LT predicate on the "recover_consecutive_successes" field.
func RecoverConsecutiveSuccessesLT(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldLT(FieldRecoverConsecutiveSuccesses, v))
}

// RecoverConsecutiveSuccessesLTE applies the LTE predicate on the "recover_consecutive_successes" field.
func RecoverConsecutiveSuccessesLTE(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldLTE(FieldRecoverConsecutiveSuccesses, v))
}

// CooldownMinutesEQ applies the EQ predicate on the "cooldown_minutes" field.
func CooldownMinutesEQ(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldEQ(FieldCooldownMinutes, v))
}

// CooldownMinutesNEQ applies the NEQ predicate on the "cooldown_minutes" field.
func CooldownMinutesNEQ(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldNEQ(FieldCooldownMinutes, v))
}

// CooldownMinutesIn applies the In predicate on the "cooldown_minutes" field.
func CooldownMinutesIn(vs ...int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldIn(FieldCooldownMinutes, vs...))
}

// CooldownMinutesNotIn applies the NotIn predicate on the "cooldown_minutes" field.
func CooldownMinutesNotIn(vs ...int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldNotIn(FieldCooldownMinutes, vs...))
}

// CooldownMinutesGT applies the GT predicate on the "cooldown_minutes" field.
func CooldownMinutesGT(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldGT(FieldCooldownMinutes, v))
}

// CooldownMinutesGTE applies the GTE predicate on the "cooldown_minutes" field.
func CooldownMinutesGTE(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldGTE(FieldCooldownMinutes, v))
}

// CooldownMinutesLT applies the LT predicate on the "cooldown_minutes" field.
func CooldownMinutesLT(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldLT(FieldCooldownMinutes, v))
}

// CooldownMinutesLTE applies the LTE predicate on the "cooldown_minutes" field.
func CooldownMinutesLTE(v int) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.FieldLTE(FieldCooldownMinutes, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SchedulingPolicy) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SchedulingPolicy) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SchedulingPolicy) predicate.SchedulingPolicy {
	return predicate.SchedulingPolicy(sql.NotPredicates(p))
}
