// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/schedulingaction"
)

// SchedulingAction is the model entity for the SchedulingAction schema.
type SchedulingAction struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// PolicyID holds the value of the "policy_id" field.
	PolicyID int64 `json:"policy_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// MonitorID holds the value of the "monitor_id" field.
	MonitorID int64 `json:"monitor_id,omitempty"`
	// pause / deprioritize / recover
	Action string `json:"action,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// deprioritize 动作执行前的账号优先级，恢复时还原
	OriginalPriority int `json:"original_priority,omitempty"`
	// 该动作是否已被恢复（recover 动作本身恒为 true）
	Restored bool `json:"restored,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SchedulingAction) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case schedulingaction.FieldRestored:
			values[i] = new(sql.NullBool)
		case schedulingaction.FieldID, schedulingaction.FieldPolicyID, schedulingaction.FieldAccountID, schedulingaction.FieldMonitorID, schedulingaction.FieldOriginalPriority:
			values[i] = new(sql.NullInt64)
		case schedulingaction.FieldAction, schedulingaction.FieldReason:
			values[i] = new(sql.NullString)
		case schedulingaction.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SchedulingAction fields.
func (_m *SchedulingAction) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case schedulingaction.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case schedulingaction.FieldPolicyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field policy_id", values[i])
			} else if value.Valid {
				_m.PolicyID = value.Int64
			}
		case schedulingaction.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case schedulingaction.FieldMonitorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field monitor_id", values[i])
			} else if value.Valid {
				_m.MonitorID = value.Int64
			}
		case schedulingaction.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = value.String
			}
		case schedulingaction.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case schedulingaction.FieldOriginalPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field original_priority", values[i])
			} else if value.Valid {
				_m.OriginalPriority = int(value.Int64)
			}
		case schedulingaction.FieldRestored:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field restored", values[i])
			} else if value.Valid {
				_m.Restored = value.Bool
			}
		case schedulingaction.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SchedulingAction.
// This includes values selected through modifiers, order, etc.
func (_m *SchedulingAction) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SchedulingAction.
// Note that you need to call SchedulingAction.Unwrap() before calling this method if this SchedulingAction
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SchedulingAction) Update() *SchedulingActionUpdateOne {
	return NewSchedulingActionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SchedulingAction entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SchedulingAction) Unwrap() *SchedulingAction {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SchedulingAction is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SchedulingAction) String() string {
	var builder strings.Builder
	builder.WriteString("SchedulingAction(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("policy_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PolicyID))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("monitor_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.MonitorID))
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(_m.Action)
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	builder.WriteString("original_priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.OriginalPriority))
	builder.WriteString(", ")
	builder.WriteString("restored=")
	builder.WriteString(fmt.Sprintf("%v", _m.Restored))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SchedulingActions is a parsable slice of SchedulingAction.
type SchedulingActions []*SchedulingAction
