// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/schedulingpolicy"
)

// SchedulingPolicy is the model entity for the SchedulingPolicy schema.
type SchedulingPolicy struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// 条件源：channel_monitors.id，监控被删除时策略停摆但保留配置
	MonitorID int64 `json:"monitor_id,omitempty"`
	// 动作目标账号 ID 列表
	AccountIds []int64 `json:"account_ids,omitempty"`
	// 连续失败 N 次后触发（failed/error 或延迟超阈值均计为失败）
	TriggerConsecutiveFailures int `json:"trigger_consecutive_failures,omitempty"`
	// 延迟阈值（毫秒），检测延迟超过该值计为一次失败；0 表示不启用延迟条件
	TriggerLatencyMs int `json:"trigger_latency_ms,omitempty"`
	// 触发动作：pause（临时停用）或 deprioritize（降低优先级）
	ActionType string `json:"action_type,omitempty"`
	// pause 动作的停用时长（分钟）；0 表示停用至恢复条件满足
	PauseMinutes int `json:"pause_minutes,omitempty"`
	// deprioritize 动作在原优先级上增加的数值（数值越大优先级越低）
	PriorityDelta int `json:"priority_delta,omitempty"`
	// 连续成功 N 次后自动恢复；0 表示不自动恢复
	RecoverConsecutiveSuccesses int `json:"recover_consecutive_successes,omitempty"`
	// 两次触发之间的最小间隔（分钟），防止抖动反复触发
	CooldownMinutes int `json:"cooldown_minutes,omitempty"`
	selectValues    sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SchedulingPolicy) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case schedulingpolicy.FieldAccountIds:
			values[i] = new([]byte)
		case schedulingpolicy.FieldEnabled:
			values[i] = new(sql.NullBool)
		case schedulingpolicy.FieldID, schedulingpolicy.FieldMonitorID, schedulingpolicy.FieldTriggerConsecutiveFailures, schedulingpolicy.FieldTriggerLatencyMs, schedulingpolicy.FieldPauseMinutes, schedulingpolicy.FieldPriorityDelta, schedulingpolicy.FieldRecoverConsecutiveSuccesses, schedulingpolicy.FieldCooldownMinutes:
			values[i] = new(sql.NullInt64)
		case schedulingpolicy.FieldName, schedulingpolicy.FieldActionType:
			values[i] = new(sql.NullString)
		case schedulingpolicy.FieldCreatedAt, schedulingpolicy.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SchedulingPolicy fields.
func (_m *SchedulingPolicy) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case schedulingpolicy.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case schedulingpolicy.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case schedulingpolicy.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case schedulingpolicy.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case schedulingpolicy.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case schedulingpolicy.FieldMonitorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field monitor_id", values[i])
			} else if value.Valid {
				_m.MonitorID = value.Int64
			}
		case schedulingpolicy.FieldAccountIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field account_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AccountIds); err != nil {
					return fmt.Errorf("unmarshal field account_ids: %w", err)
				}
			}
		case schedulingpolicy.FieldTriggerConsecutiveFailures:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_consecutive_failures", values[i])
			} else if value.Valid {
				_m.TriggerConsecutiveFailures = int(value.Int64)
			}
		case schedulingpolicy.FieldTriggerLatencyMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_latency_ms", values[i])
			} else if value.Valid {
				_m.TriggerLatencyMs = int(value.Int64)
			}
		case schedulingpolicy.FieldActionType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action_type", values[i])
			} else if value.Valid {
				_m.ActionType = value.String
			}
		case schedulingpolicy.FieldPauseMinutes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pause_minutes", values[i])
			} else if value.Valid {
				_m.PauseMinutes = int(value.Int64)
			}
		case schedulingpolicy.FieldPriorityDelta:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority_delta", values[i])
			} else if value.Valid {
				_m.PriorityDelta = int(value.Int64)
			}
		case schedulingpolicy.FieldRecoverConsecutiveSuccesses:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field recover_consecutive_successes", values[i])
			} else if value.Valid {
				_m.RecoverConsecutiveSuccesses = int(value.Int64)
			}
		case schedulingpolicy.FieldCooldownMinutes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cooldown_minutes", values[i])
			} else if value.Valid {
				_m.CooldownMinutes = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SchedulingPolicy.
// This includes values selected through modifiers, order, etc.
func (_m *SchedulingPolicy) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SchedulingPolicy.
// Note that you need to call SchedulingPolicy.Unwrap() before calling this method if this SchedulingPolicy
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SchedulingPolicy) Update() *SchedulingPolicyUpdateOne {
	return NewSchedulingPolicyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SchedulingPolicy entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SchedulingPolicy) Unwrap() *SchedulingPolicy {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SchedulingPolicy is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SchedulingPolicy) String() string {
	var builder strings.Builder
	builder.WriteString("SchedulingPolicy(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("monitor_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.MonitorID))
	builder.WriteString(", ")
	builder.WriteString("account_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountIds))
	builder.WriteString(", ")
	builder.WriteString("trigger_consecutive_failures=")
	builder.WriteString(fmt.Sprintf("%v", _m.TriggerConsecutiveFailures))
	builder.WriteString(", ")
	builder.WriteString("trigger_latency_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.TriggerLatencyMs))
	builder.WriteString(", ")
	builder.WriteString("action_type=")
	builder.WriteString(_m.ActionType)
	builder.WriteString(", ")
	builder.WriteString("pause_minutes=")
	builder.WriteString(fmt.Sprintf("%v", _m.PauseMinutes))
	builder.WriteString(", ")
	builder.WriteString("priority_delta=")
	builder.WriteString(fmt.Sprintf("%v", _m.PriorityDelta))
	builder.WriteString(", ")
	builder.WriteString("recover_consecutive_successes=")
	builder.WriteString(fmt.Sprintf("%v", _m.RecoverConsecutiveSuccesses))
	builder.WriteString(", ")
	builder.WriteString("cooldown_minutes=")
	builder.WriteString(fmt.Sprintf("%v", _m.CooldownMinutes))
	builder.WriteByte(')')
	return builder.String()
}

// SchedulingPolicies is a parsable slice of SchedulingPolicy.
type SchedulingPolicies []*SchedulingPolicy
