// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/schedulingpolicy"
)

// SchedulingPolicyCreate is the builder for creating a SchedulingPolicy entity.
type SchedulingPolicyCreate struct {
	config
	mutation *SchedulingPolicyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SchedulingPolicyCreate) SetCreatedAt(v time.Time) *SchedulingPolicyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SchedulingPolicyCreate) SetNillableCreatedAt(v *time.Time) *SchedulingPolicyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SchedulingPolicyCreate) SetUpdatedAt(v time.Time) *SchedulingPolicyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SchedulingPolicyCreate) SetNillableUpdatedAt(v *time.Time) *SchedulingPolicyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *SchedulingPolicyCreate) SetName(v string) *SchedulingPolicyCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *SchedulingPolicyCreate) SetEnabled(v bool) *SchedulingPolicyCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *SchedulingPolicyCreate) SetNillableEnabled(v *bool) *SchedulingPolicyCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetMonitorID sets the "monitor_id" field.
func (_c *SchedulingPolicyCreate) SetMonitorID(v int64) *SchedulingPolicyCreate {
	_c.mutation.SetMonitorID(v)
	return _c
}

// SetAccountIds sets the "account_ids" field.
func (_c *SchedulingPolicyCreate) SetAccountIds(v []int64) *SchedulingPolicyCreate {
	_c.mutation.SetAccountIds(v)
	return _c
}

// SetTriggerConsecutiveFailures sets the "trigger_consecutive_failures" field.
func (_c *SchedulingPolicyCreate) SetTriggerConsecutiveFailures(v int) *SchedulingPolicyCreate {
	_c.mutation.SetTriggerConsecutiveFailures(v)
	return _c
}

// SetNillableTriggerConsecutiveFailures sets the "trigger_consecutive_failures" field if the given value is not nil.
func (_c *SchedulingPolicyCreate) SetNillableTriggerConsecutiveFailures(v *int) *SchedulingPolicyCreate {
	if v != nil {
		_c.SetTriggerConsecutiveFailures(*v)
	}
	return _c
}

// SetTriggerLatencyMs sets the "trigger_latency_ms" field.
func (_c *SchedulingPolicyCreate) SetTriggerLatencyMs(v int) *SchedulingPolicyCreate {
	_c.mutation.SetTriggerLatencyMs(v)
	return _c
}

// SetNillableTriggerLatencyMs sets the "trigger_latency_ms" field if the given value is not nil.
func (_c *SchedulingPolicyCreate) SetNillableTriggerLatencyMs(v *int) *SchedulingPolicyCreate {
	if v != nil {
		_c.SetTriggerLatencyMs(*v)
	}
	return _c
}

// SetActionType sets the "action_type" field.
func (_c *SchedulingPolicyCreate) SetActionType(v string) *SchedulingPolicyCreate {
	_c.mutation.SetActionType(v)
	return _c
}

// SetNillableActionType sets the "action_type" field if the given value is not nil.
func (_c *SchedulingPolicyCreate) SetNillableActionType(v *string) *SchedulingPolicyCreate {
	if v != nil {
		_c.SetActionType(*v)
	}
	return _c
}

// SetPauseMinutes sets the "pause_minutes" field.
func (_c *SchedulingPolicyCreate) SetPauseMinutes(v int) *SchedulingPolicyCreate {
	_c.mutation.SetPauseMinutes(v)
	return _c
}

// SetNillablePauseMinutes sets the "pause_minutes" field if the given value is not nil.
func (_c *SchedulingPolicyCreate) SetNillablePauseMinutes(v *int) *SchedulingPolicyCreate {
	if v != nil {
		_c.SetPauseMinutes(*v)
	}
	return _c
}

// SetPriorityDelta sets the "priority_delta" field.
func (_c *SchedulingPolicyCreate) SetPriorityDelta(v int) *SchedulingPolicyCreate {
	_c.mutation.SetPriorityDelta(v)
	return _c
}

// SetNillablePriorityDelta sets the "priority_delta" field if the given value is not nil.
func (_c *SchedulingPolicyCreate) SetNillablePriorityDelta(v *int) *SchedulingPolicyCreate {
	if v != nil {
		_c.SetPriorityDelta(*v)
	}
	return _c
}

// SetRecoverConsecutiveSuccesses sets the "recover_consecutive_successes" field.
func (_c *SchedulingPolicyCreate) SetRecoverConsecutiveSuccesses(v int) *SchedulingPolicyCreate {
	_c.mutation.SetRecoverConsecutiveSuccesses(v)
	return _c
}

// SetNillableRecoverConsecutiveSuccesses sets the "recover_consecutive_successes" field if the given value is not nil.
func (_c *SchedulingPolicyCreate) SetNillableRecoverConsecutiveSuccesses(v *int) *SchedulingPolicyCreate {
	if v != nil {
		_c.SetRecoverConsecutiveSuccesses(*v)
	}
	return _c
}

// SetCooldownMinutes sets the "cooldown_minutes" field.
func (_c *SchedulingPolicyCreate) SetCooldownMinutes(v int) *SchedulingPolicyCreate {
	_c.mutation.SetCooldownMinutes(v)
	return _c
}

// SetNillableCooldownMinutes sets the "cooldown_minutes" field if the given value is not nil.
func (_c *SchedulingPolicyCreate) SetNillableCooldownMinutes(v *int) *SchedulingPolicyCreate {
	if v != nil {
		_c.SetCooldownMinutes(*v)
	}
	return _c
}

// Mutation returns the SchedulingPolicyMutation object of the builder.
func (_c *SchedulingPolicyCreate) Mutation() *SchedulingPolicyMutation {
	return _c.mutation
}

// Save creates the SchedulingPolicy in the database.
func (_c *SchedulingPolicyCreate) Save(ctx context.Context) (*SchedulingPolicy, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SchedulingPolicyCreate) SaveX(ctx context.Context) *SchedulingPolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SchedulingPolicyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SchedulingPolicyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SchedulingPolicyCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := schedulingpolicy.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := schedulingpolicy.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := schedulingpolicy.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.AccountIds(); !ok {
		v := schedulingpolicy.DefaultAccountIds
		_c.mutation.SetAccountIds(v)
	}
	if _, ok := _c.mutation.TriggerConsecutiveFailures(); !ok {
		v := schedulingpolicy.DefaultTriggerConsecutiveFailures
		_c.mutation.SetTriggerConsecutiveFailures(v)
	}
	if _, ok := _c.mutation.TriggerLatencyMs(); !ok {
		v := schedulingpolicy.DefaultTriggerLatencyMs
		_c.mutation.SetTriggerLatencyMs(v)
	}
	if _, ok := _c.mutation.ActionType(); !ok {
		v := schedulingpolicy.DefaultActionType
		_c.mutation.SetActionType(v)
	}
	if _, ok := _c.mutation.PauseMinutes(); !ok {
		v := schedulingpolicy.DefaultPauseMinutes
		_c.mutation.SetPauseMinutes(v)
	}
	if _, ok := _c.mutation.PriorityDelta(); !ok {
		v := schedulingpolicy.DefaultPriorityDelta
		_c.mutation.SetPriorityDelta(v)
	}
	if _, ok := _c.mutation.RecoverConsecutiveSuccesses(); !ok {
		v := schedulingpolicy.DefaultRecoverConsecutiveSuccesses
		_c.mutation.SetRecoverConsecutiveSuccesses(v)
	}
	if _, ok := _c.mutation.CooldownMinutes(); !ok {
		v := schedulingpolicy.DefaultCooldownMinutes
		_c.mutation.SetCooldownMinutes(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SchedulingPolicyCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SchedulingPolicy.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SchedulingPolicy.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SchedulingPolicy.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := schedulingpolicy.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SchedulingPolicy.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "SchedulingPolicy.enabled"`)}
	}
	if _, ok := _c.mutation.MonitorID(); !ok {
		return &ValidationError{Name: "monitor_id", err: errors.New(`ent: missing required field "SchedulingPolicy.monitor_id"`)}
	}
	if _, ok := _c.mutation.AccountIds(); !ok {
		return &ValidationError{Name: "account_ids", err: errors.New(`ent: missing required field "SchedulingPolicy.account_ids"`)}
	}
	if _, ok := _c.mutation.TriggerConsecutiveFailures(); !ok {
		return &ValidationError{Name: "trigger_consecutive_failures", err: errors.New(`ent: missing required field "SchedulingPolicy.trigger_consecutive_failures"`)}
	}
	if v, ok := _c.mutation.TriggerConsecutiveFailures(); ok {
		if err := schedulingpolicy.TriggerConsecutiveFailuresValidator(v); err != nil {
			return &ValidationError{Name: "trigger_consecutive_failures", err: fmt.Errorf(`ent: validator failed for field "SchedulingPolicy.trigger_consecutive_failures": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TriggerLatencyMs(); !ok {
		return &ValidationError{Name: "trigger_latency_ms", err: errors.New(`ent: missing required field "SchedulingPolicy.trigger_latency_ms"`)}
	}
	if v, ok := _c.mutation.TriggerLatencyMs(); ok {
		if err := schedulingpolicy.TriggerLatencyMsValidator(v); err != nil {
			return &ValidationError{Name: "trigger_latency_ms", err: fmt.Errorf(`ent: validator failed for field "SchedulingPolicy.trigger_latency_ms": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActionType(); !ok {
		return &ValidationError{Name: "action_type", err: errors.New(`ent: missing required field "SchedulingPolicy.action_type"`)}
	}
	if v, ok := _c.mutation.ActionType(); ok {
		if err := schedulingpolicy.ActionTypeValidator(v); err != nil {
			return &ValidationError{Name: "action_type", err: fmt.Errorf(`ent: validator failed for field "SchedulingPolicy.action_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PauseMinutes(); !ok {
		return &ValidationError{Name: "pause_minutes", err: errors.New(`ent: missing required field "SchedulingPolicy.pause_minutes"`)}
	}
	if v, ok := _c.mutation.PauseMinutes(); ok {
		if err := schedulingpolicy.PauseMinutesValidator(v); err != nil {
			return &ValidationError{Name: "pause_minutes", err: fmt.Errorf(`ent: validator failed for field "SchedulingPolicy.pause_minutes": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PriorityDelta(); !ok {
		return &ValidationError{Name: "priority_delta", err: errors.New(`ent: missing required field "SchedulingPolicy.priority_delta"`)}
	}
	if v, ok := _c.mutation.PriorityDelta(); ok {
		if err := schedulingpolicy.PriorityDeltaValidator(v); err != nil {
			return &ValidationError{Name: "priority_delta", err: fmt.Errorf(`ent: validator failed for field "SchedulingPolicy.priority_delta": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RecoverConsecutiveSuccesses(); !ok {
		return &ValidationError{Name: "recover_consecutive_successes", err: errors.New(`ent: missing required field "SchedulingPolicy.recover_consecutive_successes"`)}
	}
	if v, ok := _c.mutation.RecoverConsecutiveSuccesses(); ok {
		if err := schedulingpolicy.RecoverConsecutiveSuccessesValidator(v); err != nil {
			return &ValidationError{Name: "recover_consecutive_successes", err: fmt.Errorf(`ent: validator failed for field "SchedulingPolicy.recover_consecutive_successes": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CooldownMinutes(); !ok {
		return &ValidationError{Name: "cooldown_minutes", err: errors.New(`ent: missing required field "SchedulingPolicy.cooldown_minutes"`)}
	}
	if v, ok := _c.mutation.CooldownMinutes(); ok {
		if err := schedulingpolicy.CooldownMinutesValidator(v); err != nil {
			return &ValidationError{Name: "cooldown_minutes", err: fmt.Errorf(`ent: validator failed for field "SchedulingPolicy.cooldown_minutes": %w`, err)}
		}
	}
	return nil
}

func (_c *SchedulingPolicyCreate) sqlSave(ctx context.Context) (*SchedulingPolicy, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SchedulingPolicyCreate) createSpec() (*SchedulingPolicy, *sqlgraph.CreateSpec) {
	var (
		_node = &SchedulingPolicy{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(schedulingpolicy.Table, sqlgraph.NewFieldSpec(schedulingpolicy.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(schedulingpolicy.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(schedulingpolicy.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(schedulingpolicy.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(schedulingpolicy.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.MonitorID(); ok {
		_spec.SetField(schedulingpolicy.FieldMonitorID, field.TypeInt64, value)
		_node.MonitorID = value
	}
	if value, ok := _c.mutation.AccountIds(); ok {
		_spec.SetField(schedulingpolicy.FieldAccountIds, field.TypeJSON, value)
		_node.AccountIds = value
	}
	if value, ok := _c.mutation.TriggerConsecutiveFailures(); ok {
		_spec.SetField(schedulingpolicy.FieldTriggerConsecutiveFailures, field.TypeInt, value)
		_node.TriggerConsecutiveFailures = value
	}
	if value, ok := _c.mutation.TriggerLatencyMs(); ok {
		_spec.SetField(schedulingpolicy.FieldTriggerLatencyMs, field.TypeInt, value)
		_node.TriggerLatencyMs = value
	}
	if value, ok := _c.mutation.ActionType(); ok {
		_spec.SetField(schedulingpolicy.FieldActionType, field.TypeString, value)
		_node.ActionType = value
	}
	if value, ok := _c.mutation.PauseMinutes(); ok {
		_spec.SetField(schedulingpolicy.FieldPauseMinutes, field.TypeInt, value)
		_node.PauseMinutes = value
	}
	if value, ok := _c.mutation.PriorityDelta(); ok {
		_spec.SetField(schedulingpolicy.FieldPriorityDelta, field.TypeInt, value)
		_node.PriorityDelta = value
	}
	if value, ok := _c.mutation.RecoverConsecutiveSuccesses(); ok {
		_spec.SetField(schedulingpolicy.FieldRecoverConsecutiveSuccesses, field.TypeInt, value)
		_node.RecoverConsecutiveSuccesses = value
	}
	if value, ok := _c.mutation.CooldownMinutes(); ok {
		_spec.SetField(schedulingpolicy.FieldCooldownMinutes, field.TypeInt, value)
		_node.CooldownMinutes = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SchedulingPolicy.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SchedulingPolicyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SchedulingPolicyCreate) OnConflict(opts ...sql.ConflictOption) *SchedulingPolicyUpsertOne {
	_c.conflict = opts
	return &SchedulingPolicyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SchedulingPolicy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SchedulingPolicyCreate) OnConflictColumns(columns ...string) *SchedulingPolicyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SchedulingPolicyUpsertOne{
		create: _c,
	}
}

type (
	// SchedulingPolicyUpsertOne is the builder for "upsert"-ing
	//  one SchedulingPolicy node.
	SchedulingPolicyUpsertOne struct {
		create *SchedulingPolicyCreate
	}

	// SchedulingPolicyUpsert is the "OnConflict" setter.
	SchedulingPolicyUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SchedulingPolicyUpsert) SetUpdatedAt(v time.Time) *SchedulingPolicyUpsert {
	u.Set(schedulingpolicy.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SchedulingPolicyUpsert) UpdateUpdatedAt() *SchedulingPolicyUpsert {
	u.SetExcluded(schedulingpolicy.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *SchedulingPolicyUpsert) SetName(v string) *SchedulingPolicyUpsert {
	u.Set(schedulingpolicy.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SchedulingPolicyUpsert) UpdateName() *SchedulingPolicyUpsert {
	u.SetExcluded(schedulingpolicy.FieldName)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *SchedulingPolicyUpsert) SetEnabled(v bool) *SchedulingPolicyUpsert {
	u.Set(schedulingpolicy.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *SchedulingPolicyUpsert) UpdateEnabled() *SchedulingPolicyUpsert {
	u.SetExcluded(schedulingpolicy.FieldEnabled)
	return u
}

// SetMonitorID sets the "monitor_id" field.
func (u *SchedulingPolicyUpsert) SetMonitorID(v int64) *SchedulingPolicyUpsert {
	u.Set(schedulingpolicy.FieldMonitorID, v)
	return u
}

// UpdateMonitorID sets the "monitor_id" field to the value that was provided on create.
func (u *SchedulingPolicyUpsert) UpdateMonitorID() *SchedulingPolicyUpsert {
	u.SetExcluded(schedulingpolicy.FieldMonitorID)
	return u
}

// AddMonitorID adds v to the "monitor_id" field.
func (u *SchedulingPolicyUpsert) AddMonitorID(v int64) *SchedulingPolicyUpsert {
	u.Add(schedulingpolicy.FieldMonitorID, v)
	return u
}

// SetAccountIds sets the "account_ids" field.
func (u *SchedulingPolicyUpsert) SetAccountIds(v []int64) *SchedulingPolicyUpsert {
	u.Set(schedulingpolicy.FieldAccountIds, v)
	return u
}

// UpdateAccountIds sets the "account_ids" field to the value that was provided on create.
func (u *SchedulingPolicyUpsert) UpdateAccountIds() *SchedulingPolicyUpsert {
	u.SetExcluded(schedulingpolicy.FieldAccountIds)
	return u
}

// SetTriggerConsecutiveFailures sets the "trigger_consecutive_failures" field.
func (u *SchedulingPolicyUpsert) SetTriggerConsecutiveFailures(v int) *SchedulingPolicyUpsert {
	u.Set(schedulingpolicy.FieldTriggerConsecutiveFailures, v)
	return u
}

// UpdateTriggerConsecutiveFailures sets the "trigger_consecutive_failures" field to the value that was provided on create.
func (u *SchedulingPolicyUpsert) UpdateTriggerConsecutiveFailures() *SchedulingPolicyUpsert {
	u.SetExcluded(schedulingpolicy.FieldTriggerConsecutiveFailures)
	return u
}

// AddTriggerConsecutiveFailures adds v to the "trigger_consecutive_failures" field.
func (u *SchedulingPolicyUpsert) AddTriggerConsecutiveFailures(v int) *SchedulingPolicyUpsert {
	u.Add(schedulingpolicy.FieldTriggerConsecutiveFailures, v)
	return u
}

// SetTriggerLatencyMs sets the "trigger_latency_ms" field.
func (u *SchedulingPolicyUpsert) SetTriggerLatencyMs(v int) *SchedulingPolicyUpsert {
	u.Set(schedulingpolicy.FieldTriggerLatencyMs, v)
	return u
}

// UpdateTriggerLatencyMs sets the "trigger_latency_ms" field to the value that was provided on create.
func (u *SchedulingPolicyUpsert) UpdateTriggerLatencyMs() *SchedulingPolicyUpsert {
	u.SetExcluded(schedulingpolicy.FieldTriggerLatencyMs)
	return u
}

// AddTriggerLatencyMs adds v to the "trigger_latency_ms" field.
func (u *SchedulingPolicyUpsert) AddTriggerLatencyMs(v int) *SchedulingPolicyUpsert {
	u.Add(schedulingpolicy.FieldTriggerLatencyMs, v)
	return u
}

// SetActionType sets the "action_type" field.
func (u *SchedulingPolicyUpsert) SetActionType(v string) *SchedulingPolicyUpsert {
	u.Set(schedulingpolicy.FieldActionType, v)
	return u
}

// UpdateActionType sets the "action_type" field to the value that was provided on create.
func (u *SchedulingPolicyUpsert) UpdateActionType() *SchedulingPolicyUpsert {
	u.SetExcluded(schedulingpolicy.FieldActionType)
	return u
}

// SetPauseMinutes sets the "pause_minutes" field.
func (u *SchedulingPolicyUpsert) SetPauseMinutes(v int) *SchedulingPolicyUpsert {
	u.Set(schedulingpolicy.FieldPauseMinutes, v)
	return u
}

// UpdatePauseMinutes sets the "pause_minutes" field to the value that was provided on create.
func (u *SchedulingPolicyUpsert) UpdatePauseMinutes() *SchedulingPolicyUpsert {
	u.SetExcluded(schedulingpolicy.FieldPauseMinutes)
	return u
}

// AddPauseMinutes adds v to the "pause_minutes" field.
func (u *SchedulingPolicyUpsert) AddPauseMinutes(v int) *SchedulingPolicyUpsert {
	u.Add(schedulingpolicy.FieldPauseMinutes, v)
	return u
}

// SetPriorityDelta sets the "priority_delta" field.
func (u *SchedulingPolicyUpsert) SetPriorityDelta(v int) *SchedulingPolicyUpsert {
	u.Set(schedulingpolicy.FieldPriorityDelta, v)
	return u
}

// UpdatePriorityDelta sets the "priority_delta" field to the value that was provided on create.
func (u *SchedulingPolicyUpsert) UpdatePriorityDelta() *SchedulingPolicyUpsert {
	u.SetExcluded(schedulingpolicy.FieldPriorityDelta)
	return u
}

// AddPriorityDelta adds v to the "priority_delta" field.
func (u *SchedulingPolicyUpsert) AddPriorityDelta(v int) *SchedulingPolicyUpsert {
	u.Add(schedulingpolicy.FieldPriorityDelta, v)
	return u
}

// SetRecoverConsecutiveSuccesses sets the "recover_consecutive_successes" field.
func (u *SchedulingPolicyUpsert) SetRecoverConsecutiveSuccesses(v int) *SchedulingPolicyUpsert {
	u.Set(schedulingpolicy.FieldRecoverConsecutiveSuccesses, v)
	return u
}

// UpdateRecoverConsecutiveSuccesses sets the "recover_consecutive_successes" field to the value that was provided on create.
func (u *SchedulingPolicyUpsert) UpdateRecoverConsecutiveSuccesses() *SchedulingPolicyUpsert {
	u.SetExcluded(schedulingpolicy.FieldRecoverConsecutiveSuccesses)
	return u
}

// AddRecoverConsecutiveSuccesses adds v to the "recover_consecutive_successes" field.
func (u *SchedulingPolicyUpsert) AddRecoverConsecutiveSuccesses(v int) *SchedulingPolicyUpsert {
	u.Add(schedulingpolicy.FieldRecoverConsecutiveSuccesses, v)
	return u
}

// SetCooldownMinutes sets the "cooldown_minutes" field.
func (u *SchedulingPolicyUpsert) SetCooldownMinutes(v int) *SchedulingPolicyUpsert {
	u.Set(schedulingpolicy.FieldCooldownMinutes, v)
	return u
}

// UpdateCooldownMinutes sets the "cooldown_minutes" field to the value that was provided on create.
func (u *SchedulingPolicyUpsert) UpdateCooldownMinutes() *SchedulingPolicyUpsert {
	u.SetExcluded(schedulingpolicy.FieldCooldownMinutes)
	return u
}

// AddCooldownMinutes adds v to the "cooldown_minutes" field.
func (u *SchedulingPolicyUpsert) AddCooldownMinutes(v int) *SchedulingPolicyUpsert {
	u.Add(schedulingpolicy.FieldCooldownMinutes, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SchedulingPolicy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SchedulingPolicyUpsertOne) UpdateNewValues() *SchedulingPolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(schedulingpolicy.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SchedulingPolicy.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SchedulingPolicyUpsertOne) Ignore() *SchedulingPolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SchedulingPolicyUpsertOne) DoNothing() *SchedulingPolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SchedulingPolicyCreate.OnConflict
// documentation for more info.
func (u *SchedulingPolicyUpsertOne) Update(set func(*SchedulingPolicyUpsert)) *SchedulingPolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SchedulingPolicyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SchedulingPolicyUpsertOne) SetUpdatedAt(v time.Time) *SchedulingPolicyUpsertOne {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SchedulingPolicyUpsertOne) UpdateUpdatedAt() *SchedulingPolicyUpsertOne {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *SchedulingPolicyUpsertOne) SetName(v string) *SchedulingPolicyUpsertOne {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SchedulingPolicyUpsertOne) UpdateName() *SchedulingPolicyUpsertOne {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.UpdateName()
	})
}

// SetEnabled sets the "enabled" field.
func (u *SchedulingPolicyUpsertOne) SetEnabled(v bool) *SchedulingPolicyUpsertOne {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *SchedulingPolicyUpsertOne) UpdateEnabled() *SchedulingPolicyUpsertOne {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.UpdateEnabled()
	})
}

// SetMonitorID sets the "monitor_id" field.
func (u *SchedulingPolicyUpsertOne) SetMonitorID(v int64) *SchedulingPolicyUpsertOne {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.SetMonitorID(v)
	})
}

// AddMonitorID adds v to the "monitor_id" field.
func (u *SchedulingPolicyUpsertOne) AddMonitorID(v int64) *SchedulingPolicyUpsertOne {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.AddMonitorID(v)
	})
}

// UpdateMonitorID sets the "monitor_id" field to the value that was provided on create.
func (u *SchedulingPolicyUpsertOne) UpdateMonitorID() *SchedulingPolicyUpsertOne {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.UpdateMonitorID()
	})
}

// SetAccountIds sets the "account_ids" field.
func (u *SchedulingPolicyUpsertOne) SetAccountIds(v []int64) *SchedulingPolicyUpsertOne {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.SetAccountIds(v)
	})
}

// UpdateAccountIds sets the "account_ids" field to the value that was provided on create.
func (u *SchedulingPolicyUpsertOne) UpdateAccountIds() *SchedulingPolicyUpsertOne {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.UpdateAccountIds()
	})
}

// SetTriggerConsecutiveFailures sets the "trigger_consecutive_failures" field.
func (u *SchedulingPolicyUpsertOne) SetTriggerConsecutiveFailures(v int) *SchedulingPolicyUpsertOne {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.SetTriggerConsecutiveFailures(v)
	})
}

// AddTriggerConsecutiveFailures adds v to the "trigger_consecutive_failures" field.
func (u *SchedulingPolicyUpsertOne) AddTriggerConsecutiveFailures(v int) *SchedulingPolicyUpsertOne {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.AddTriggerConsecutiveFailures(v)
	})
}

// UpdateTriggerConsecutiveFailures sets the "trigger_consecutive_failures" field to the value that was provided on create.
func (u *SchedulingPolicyUpsertOne) UpdateTriggerConsecutiveFailures() *SchedulingPolicyUpsertOne {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.UpdateTriggerConsecutiveFailures()
	})
}

// SetTriggerLatencyMs sets the "trigger_latency_ms" field.
func (u *SchedulingPolicyUpsertOne) SetTriggerLatencyMs(v int) *SchedulingPolicyUpsertOne {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.SetTriggerLatencyMs(v)
	})
}

// AddTriggerLatencyMs adds v to the "trigger_latency_ms" field.
func (u *SchedulingPolicyUpsertOne) AddTriggerLatencyMs(v int) *SchedulingPolicyUpsertOne {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.AddTriggerLatencyMs(v)
	})
}

// UpdateTriggerLatencyMs sets the "trigger_latency_ms" field to the value that was provided on create.
func (u *SchedulingPolicyUpsertOne) UpdateTriggerLatencyMs() *SchedulingPolicyUpsertOne {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.UpdateTriggerLatencyMs()
	})
}

// SetActionType sets the "action_type" field.
func (u *SchedulingPolicyUpsertOne) SetActionType(v string) *SchedulingPolicyUpsertOne {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.SetActionType(v)
	})
}

// UpdateActionType sets the "action_type" field to the value that was provided on create.
func (u *SchedulingPolicyUpsertOne) UpdateActionType() *SchedulingPolicyUpsertOne {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.UpdateActionType()
	})
}

// SetPauseMinutes sets the "pause_minutes" field.
func (u *SchedulingPolicyUpsertOne) SetPauseMinutes(v int) *SchedulingPolicyUpsertOne {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.SetPauseMinutes(v)
	})
}

// AddPauseMinutes adds v to the "pause_minutes" field.
func (u *SchedulingPolicyUpsertOne) AddPauseMinutes(v int) *SchedulingPolicyUpsertOne {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.AddPauseMinutes(v)
	})
}

// UpdatePauseMinutes sets the "pause_minutes" field to the value that was provided on create.
func (u *SchedulingPolicyUpsertOne) UpdatePauseMinutes() *SchedulingPolicyUpsertOne {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.UpdatePauseMinutes()
	})
}

// SetPriorityDelta sets the "priority_delta" field.
func (u *SchedulingPolicyUpsertOne) SetPriorityDelta(v int) *SchedulingPolicyUpsertOne {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.SetPriorityDelta(v)
	})
}

// AddPriorityDelta adds v to the "priority_delta" field.
func (u *SchedulingPolicyUpsertOne) AddPriorityDelta(v int) *SchedulingPolicyUpsertOne {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.AddPriorityDelta(v)
	})
}

// UpdatePriorityDelta sets the "priority_delta" field to the value that was provided on create.
func (u *SchedulingPolicyUpsertOne) UpdatePriorityDelta() *SchedulingPolicyUpsertOne {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.UpdatePriorityDelta()
	})
}

// SetRecoverConsecutiveSuccesses sets the "recover_consecutive_successes" field.
func (u *SchedulingPolicyUpsertOne) SetRecoverConsecutiveSuccesses(v int) *SchedulingPolicyUpsertOne {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.SetRecoverConsecutiveSuccesses(v)
	})
}

// AddRecoverConsecutiveSuccesses adds v to the "recover_consecutive_successes" field.
func (u *SchedulingPolicyUpsertOne) AddRecoverConsecutiveSuccesses(v int) *SchedulingPolicyUpsertOne {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.AddRecoverConsecutiveSuccesses(v)
	})
}

// UpdateRecoverConsecutiveSuccesses sets the "recover_consecutive_successes" field to the value that was provided on create.
func (u *SchedulingPolicyUpsertOne) UpdateRecoverConsecutiveSuccesses() *SchedulingPolicyUpsertOne {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.UpdateRecoverConsecutiveSuccesses()
	})
}

// SetCooldownMinutes sets the "cooldown_minutes" field.
func (u *SchedulingPolicyUpsertOne) SetCooldownMinutes(v int) *SchedulingPolicyUpsertOne {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.SetCooldownMinutes(v)
	})
}

// AddCooldownMinutes adds v to the "cooldown_minutes" field.
func (u *SchedulingPolicyUpsertOne) AddCooldownMinutes(v int) *SchedulingPolicyUpsertOne {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.AddCooldownMinutes(v)
	})
}

// UpdateCooldownMinutes sets the "cooldown_minutes" field to the value that was provided on create.
func (u *SchedulingPolicyUpsertOne) UpdateCooldownMinutes() *SchedulingPolicyUpsertOne {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.UpdateCooldownMinutes()
	})
}

// Exec executes the query.
func (u *SchedulingPolicyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SchedulingPolicyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SchedulingPolicyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SchedulingPolicyUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SchedulingPolicyUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SchedulingPolicyCreateBulk is the builder for creating many SchedulingPolicy entities in bulk.
type SchedulingPolicyCreateBulk struct {
	config
	err      error
	builders []*SchedulingPolicyCreate
	conflict []sql.ConflictOption
}

// Save creates the SchedulingPolicy entities in the database.
func (_c *SchedulingPolicyCreateBulk) Save(ctx context.Context) ([]*SchedulingPolicy, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SchedulingPolicy, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SchedulingPolicyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SchedulingPolicyCreateBulk) SaveX(ctx context.Context) []*SchedulingPolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SchedulingPolicyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SchedulingPolicyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SchedulingPolicy.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SchedulingPolicyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SchedulingPolicyCreateBulk) OnConflict(opts ...sql.ConflictOption) *SchedulingPolicyUpsertBulk {
	_c.conflict = opts
	return &SchedulingPolicyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SchedulingPolicy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SchedulingPolicyCreateBulk) OnConflictColumns(columns ...string) *SchedulingPolicyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SchedulingPolicyUpsertBulk{
		create: _c,
	}
}

// SchedulingPolicyUpsertBulk is the builder for "upsert"-ing
// a bulk of SchedulingPolicy nodes.
type SchedulingPolicyUpsertBulk struct {
	create *SchedulingPolicyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SchedulingPolicy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SchedulingPolicyUpsertBulk) UpdateNewValues() *SchedulingPolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(schedulingpolicy.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SchedulingPolicy.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SchedulingPolicyUpsertBulk) Ignore() *SchedulingPolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SchedulingPolicyUpsertBulk) DoNothing() *SchedulingPolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SchedulingPolicyCreateBulk.OnConflict
// documentation for more info.
func (u *SchedulingPolicyUpsertBulk) Update(set func(*SchedulingPolicyUpsert)) *SchedulingPolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SchedulingPolicyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SchedulingPolicyUpsertBulk) SetUpdatedAt(v time.Time) *SchedulingPolicyUpsertBulk {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SchedulingPolicyUpsertBulk) UpdateUpdatedAt() *SchedulingPolicyUpsertBulk {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *SchedulingPolicyUpsertBulk) SetName(v string) *SchedulingPolicyUpsertBulk {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SchedulingPolicyUpsertBulk) UpdateName() *SchedulingPolicyUpsertBulk {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.UpdateName()
	})
}

// SetEnabled sets the "enabled" field.
func (u *SchedulingPolicyUpsertBulk) SetEnabled(v bool) *SchedulingPolicyUpsertBulk {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *SchedulingPolicyUpsertBulk) UpdateEnabled() *SchedulingPolicyUpsertBulk {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.UpdateEnabled()
	})
}

// SetMonitorID sets the "monitor_id" field.
func (u *SchedulingPolicyUpsertBulk) SetMonitorID(v int64) *SchedulingPolicyUpsertBulk {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.SetMonitorID(v)
	})
}

// AddMonitorID adds v to the "monitor_id" field.
func (u *SchedulingPolicyUpsertBulk) AddMonitorID(v int64) *SchedulingPolicyUpsertBulk {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.AddMonitorID(v)
	})
}

// UpdateMonitorID sets the "monitor_id" field to the value that was provided on create.
func (u *SchedulingPolicyUpsertBulk) UpdateMonitorID() *SchedulingPolicyUpsertBulk {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.UpdateMonitorID()
	})
}

// SetAccountIds sets the "account_ids" field.
func (u *SchedulingPolicyUpsertBulk) SetAccountIds(v []int64) *SchedulingPolicyUpsertBulk {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.SetAccountIds(v)
	})
}

// UpdateAccountIds sets the "account_ids" field to the value that was provided on create.
func (u *SchedulingPolicyUpsertBulk) UpdateAccountIds() *SchedulingPolicyUpsertBulk {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.UpdateAccountIds()
	})
}

// SetTriggerConsecutiveFailures sets the "trigger_consecutive_failures" field.
func (u *SchedulingPolicyUpsertBulk) SetTriggerConsecutiveFailures(v int) *SchedulingPolicyUpsertBulk {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.SetTriggerConsecutiveFailures(v)
	})
}

// AddTriggerConsecutiveFailures adds v to the "trigger_consecutive_failures" field.
func (u *SchedulingPolicyUpsertBulk) AddTriggerConsecutiveFailures(v int) *SchedulingPolicyUpsertBulk {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.AddTriggerConsecutiveFailures(v)
	})
}

// UpdateTriggerConsecutiveFailures sets the "trigger_consecutive_failures" field to the value that was provided on create.
func (u *SchedulingPolicyUpsertBulk) UpdateTriggerConsecutiveFailures() *SchedulingPolicyUpsertBulk {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.UpdateTriggerConsecutiveFailures()
	})
}

// SetTriggerLatencyMs sets the "trigger_latency_ms" field.
func (u *SchedulingPolicyUpsertBulk) SetTriggerLatencyMs(v int) *SchedulingPolicyUpsertBulk {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.SetTriggerLatencyMs(v)
	})
}

// AddTriggerLatencyMs adds v to the "trigger_latency_ms" field.
func (u *SchedulingPolicyUpsertBulk) AddTriggerLatencyMs(v int) *SchedulingPolicyUpsertBulk {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.AddTriggerLatencyMs(v)
	})
}

// UpdateTriggerLatencyMs sets the "trigger_latency_ms" field to the value that was provided on create.
func (u *SchedulingPolicyUpsertBulk) UpdateTriggerLatencyMs() *SchedulingPolicyUpsertBulk {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.UpdateTriggerLatencyMs()
	})
}

// SetActionType sets the "action_type" field.
func (u *SchedulingPolicyUpsertBulk) SetActionType(v string) *SchedulingPolicyUpsertBulk {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.SetActionType(v)
	})
}

// UpdateActionType sets the "action_type" field to the value that was provided on create.
func (u *SchedulingPolicyUpsertBulk) UpdateActionType() *SchedulingPolicyUpsertBulk {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.UpdateActionType()
	})
}

// SetPauseMinutes sets the "pause_minutes" field.
func (u *SchedulingPolicyUpsertBulk) SetPauseMinutes(v int) *SchedulingPolicyUpsertBulk {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.SetPauseMinutes(v)
	})
}

// AddPauseMinutes adds v to the "pause_minutes" field.
func (u *SchedulingPolicyUpsertBulk) AddPauseMinutes(v int) *SchedulingPolicyUpsertBulk {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.AddPauseMinutes(v)
	})
}

// UpdatePauseMinutes sets the "pause_minutes" field to the value that was provided on create.
func (u *SchedulingPolicyUpsertBulk) UpdatePauseMinutes() *SchedulingPolicyUpsertBulk {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.UpdatePauseMinutes()
	})
}

// SetPriorityDelta sets the "priority_delta" field.
func (u *SchedulingPolicyUpsertBulk) SetPriorityDelta(v int) *SchedulingPolicyUpsertBulk {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.SetPriorityDelta(v)
	})
}

// AddPriorityDelta adds v to the "priority_delta" field.
func (u *SchedulingPolicyUpsertBulk) AddPriorityDelta(v int) *SchedulingPolicyUpsertBulk {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.AddPriorityDelta(v)
	})
}

// UpdatePriorityDelta sets the "priority_delta" field to the value that was provided on create.
func (u *SchedulingPolicyUpsertBulk) UpdatePriorityDelta() *SchedulingPolicyUpsertBulk {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.UpdatePriorityDelta()
	})
}

// SetRecoverConsecutiveSuccesses sets the "recover_consecutive_successes" field.
func (u *SchedulingPolicyUpsertBulk) SetRecoverConsecutiveSuccesses(v int) *SchedulingPolicyUpsertBulk {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.SetRecoverConsecutiveSuccesses(v)
	})
}

// AddRecoverConsecutiveSuccesses adds v to the "recover_consecutive_successes" field.
func (u *SchedulingPolicyUpsertBulk) AddRecoverConsecutiveSuccesses(v int) *SchedulingPolicyUpsertBulk {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.AddRecoverConsecutiveSuccesses(v)
	})
}

// UpdateRecoverConsecutiveSuccesses sets the "recover_consecutive_successes" field to the value that was provided on create.
func (u *SchedulingPolicyUpsertBulk) UpdateRecoverConsecutiveSuccesses() *SchedulingPolicyUpsertBulk {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.UpdateRecoverConsecutiveSuccesses()
	})
}

// SetCooldownMinutes sets the "cooldown_minutes" field.
func (u *SchedulingPolicyUpsertBulk) SetCooldownMinutes(v int) *SchedulingPolicyUpsertBulk {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.SetCooldownMinutes(v)
	})
}

// AddCooldownMinutes adds v to the "cooldown_minutes" field.
func (u *SchedulingPolicyUpsertBulk) AddCooldownMinutes(v int) *SchedulingPolicyUpsertBulk {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.AddCooldownMinutes(v)
	})
}

// UpdateCooldownMinutes sets the "cooldown_minutes" field to the value that was provided on create.
func (u *SchedulingPolicyUpsertBulk) UpdateCooldownMinutes() *SchedulingPolicyUpsertBulk {
	return u.Update(func(s *SchedulingPolicyUpsert) {
		s.UpdateCooldownMinutes()
	})
}

// Exec executes the query.
func (u *SchedulingPolicyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SchedulingPolicyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SchedulingPolicyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SchedulingPolicyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
