// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/schedulingaction"
)

// SchedulingActionCreate is the builder for creating a SchedulingAction entity.
type SchedulingActionCreate struct {
	config
	mutation *SchedulingActionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPolicyID sets the "policy_id" field.
func (_c *SchedulingActionCreate) SetPolicyID(v int64) *SchedulingActionCreate {
	_c.mutation.SetPolicyID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *SchedulingActionCreate) SetAccountID(v int64) *SchedulingActionCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetMonitorID sets the "monitor_id" field.
func (_c *SchedulingActionCreate) SetMonitorID(v int64) *SchedulingActionCreate {
	_c.mutation.SetMonitorID(v)
	return _c
}

// SetAction sets the "action" field.
func (_c *SchedulingActionCreate) SetAction(v string) *SchedulingActionCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetReason sets the "reason" field.
func (_c *SchedulingActionCreate) SetReason(v string) *SchedulingActionCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *SchedulingActionCreate) SetNillableReason(v *string) *SchedulingActionCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetOriginalPriority sets the "original_priority" field.
func (_c *SchedulingActionCreate) SetOriginalPriority(v int) *SchedulingActionCreate {
	_c.mutation.SetOriginalPriority(v)
	return _c
}

// SetNillableOriginalPriority sets the "original_priority" field if the given value is not nil.
func (_c *SchedulingActionCreate) SetNillableOriginalPriority(v *int) *SchedulingActionCreate {
	if v != nil {
		_c.SetOriginalPriority(*v)
	}
	return _c
}

// SetRestored sets the "restored" field.
func (_c *SchedulingActionCreate) SetRestored(v bool) *SchedulingActionCreate {
	_c.mutation.SetRestored(v)
	return _c
}

// SetNillableRestored sets the "restored" field if the given value is not nil.
func (_c *SchedulingActionCreate) SetNillableRestored(v *bool) *SchedulingActionCreate {
	if v != nil {
		_c.SetRestored(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SchedulingActionCreate) SetCreatedAt(v time.Time) *SchedulingActionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// Mutation returns the SchedulingActionMutation object of the builder.
func (_c *SchedulingActionCreate) Mutation() *SchedulingActionMutation {
	return _c.mutation
}

// Save creates the SchedulingAction in the database.
func (_c *SchedulingActionCreate) Save(ctx context.Context) (*SchedulingAction, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SchedulingActionCreate) SaveX(ctx context.Context) *SchedulingAction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SchedulingActionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SchedulingActionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SchedulingActionCreate) defaults() {
	if _, ok := _c.mutation.Reason(); !ok {
		v := schedulingaction.DefaultReason
		_c.mutation.SetReason(v)
	}
	if _, ok := _c.mutation.OriginalPriority(); !ok {
		v := schedulingaction.DefaultOriginalPriority
		_c.mutation.SetOriginalPriority(v)
	}
	if _, ok := _c.mutation.Restored(); !ok {
		v := schedulingaction.DefaultRestored
		_c.mutation.SetRestored(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SchedulingActionCreate) check() error {
	if _, ok := _c.mutation.PolicyID(); !ok {
		return &ValidationError{Name: "policy_id", err: errors.New(`ent: missing required field "SchedulingAction.policy_id"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "SchedulingAction.account_id"`)}
	}
	if _, ok := _c.mutation.MonitorID(); !ok {
		return &ValidationError{Name: "monitor_id", err: errors.New(`ent: missing required field "SchedulingAction.monitor_id"`)}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "SchedulingAction.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := schedulingaction.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "SchedulingAction.action": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "SchedulingAction.reason"`)}
	}
	if v, ok := _c.mutation.Reason(); ok {
		if err := schedulingaction.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "SchedulingAction.reason": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OriginalPriority(); !ok {
		return &ValidationError{Name: "original_priority", err: errors.New(`ent: missing required field "SchedulingAction.original_priority"`)}
	}
	if _, ok := _c.mutation.Restored(); !ok {
		return &ValidationError{Name: "restored", err: errors.New(`ent: missing required field "SchedulingAction.restored"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SchedulingAction.created_at"`)}
	}
	return nil
}

func (_c *SchedulingActionCreate) sqlSave(ctx context.Context) (*SchedulingAction, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SchedulingActionCreate) createSpec() (*SchedulingAction, *sqlgraph.CreateSpec) {
	var (
		_node = &SchedulingAction{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(schedulingaction.Table, sqlgraph.NewFieldSpec(schedulingaction.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.PolicyID(); ok {
		_spec.SetField(schedulingaction.FieldPolicyID, field.TypeInt64, value)
		_node.PolicyID = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(schedulingaction.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.MonitorID(); ok {
		_spec.SetField(schedulingaction.FieldMonitorID, field.TypeInt64, value)
		_node.MonitorID = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(schedulingaction.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(schedulingaction.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.OriginalPriority(); ok {
		_spec.SetField(schedulingaction.FieldOriginalPriority, field.TypeInt, value)
		_node.OriginalPriority = value
	}
	if value, ok := _c.mutation.Restored(); ok {
		_spec.SetField(schedulingaction.FieldRestored, field.TypeBool, value)
		_node.Restored = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(schedulingaction.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SchedulingAction.Create().
//		SetPolicyID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SchedulingActionUpsert) {
//			SetPolicyID(v+v).
//		}).
//		Exec(ctx)
func (_c *SchedulingActionCreate) OnConflict(opts ...sql.ConflictOption) *SchedulingActionUpsertOne {
	_c.conflict = opts
	return &SchedulingActionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SchedulingAction.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SchedulingActionCreate) OnConflictColumns(columns ...string) *SchedulingActionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SchedulingActionUpsertOne{
		create: _c,
	}
}

type (
	// SchedulingActionUpsertOne is the builder for "upsert"-ing
	//  one SchedulingAction node.
	SchedulingActionUpsertOne struct {
		create *SchedulingActionCreate
	}

	// SchedulingActionUpsert is the "OnConflict" setter.
	SchedulingActionUpsert struct {
		*sql.UpdateSet
	}
)

// SetPolicyID sets the "policy_id" field.
func (u *SchedulingActionUpsert) SetPolicyID(v int64) *SchedulingActionUpsert {
	u.Set(schedulingaction.FieldPolicyID, v)
	return u
}

// UpdatePolicyID sets the "policy_id" field to the value that was provided on create.
func (u *SchedulingActionUpsert) UpdatePolicyID() *SchedulingActionUpsert {
	u.SetExcluded(schedulingaction.FieldPolicyID)
	return u
}

// AddPolicyID adds v to the "policy_id" field.
func (u *SchedulingActionUpsert) AddPolicyID(v int64) *SchedulingActionUpsert {
	u.Add(schedulingaction.FieldPolicyID, v)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *SchedulingActionUpsert) SetAccountID(v int64) *SchedulingActionUpsert {
	u.Set(schedulingaction.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *SchedulingActionUpsert) UpdateAccountID() *SchedulingActionUpsert {
	u.SetExcluded(schedulingaction.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *SchedulingActionUpsert) AddAccountID(v int64) *SchedulingActionUpsert {
	u.Add(schedulingaction.FieldAccountID, v)
	return u
}

// SetMonitorID sets the "monitor_id" field.
func (u *SchedulingActionUpsert) SetMonitorID(v int64) *SchedulingActionUpsert {
	u.Set(schedulingaction.FieldMonitorID, v)
	return u
}

// UpdateMonitorID sets the "monitor_id" field to the value that was provided on create.
func (u *SchedulingActionUpsert) UpdateMonitorID() *SchedulingActionUpsert {
	u.SetExcluded(schedulingaction.FieldMonitorID)
	return u
}

// AddMonitorID adds v to the "monitor_id" field.
func (u *SchedulingActionUpsert) AddMonitorID(v int64) *SchedulingActionUpsert {
	u.Add(schedulingaction.FieldMonitorID, v)
	return u
}

// SetAction sets the "action" field.
func (u *SchedulingActionUpsert) SetAction(v string) *SchedulingActionUpsert {
	u.Set(schedulingaction.FieldAction, v)
	return u
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *SchedulingActionUpsert) UpdateAction() *SchedulingActionUpsert {
	u.SetExcluded(schedulingaction.FieldAction)
	return u
}

// SetReason sets the "reason" field.
func (u *SchedulingActionUpsert) SetReason(v string) *SchedulingActionUpsert {
	u.Set(schedulingaction.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *SchedulingActionUpsert) UpdateReason() *SchedulingActionUpsert {
	u.SetExcluded(schedulingaction.FieldReason)
	return u
}

// SetOriginalPriority sets the "original_priority" field.
func (u *SchedulingActionUpsert) SetOriginalPriority(v int) *SchedulingActionUpsert {
	u.Set(schedulingaction.FieldOriginalPriority, v)
	return u
}

// UpdateOriginalPriority sets the "original_priority" field to the value that was provided on create.
func (u *SchedulingActionUpsert) UpdateOriginalPriority() *SchedulingActionUpsert {
	u.SetExcluded(schedulingaction.FieldOriginalPriority)
	return u
}

// AddOriginalPriority adds v to the "original_priority" field.
func (u *SchedulingActionUpsert) AddOriginalPriority(v int) *SchedulingActionUpsert {
	u.Add(schedulingaction.FieldOriginalPriority, v)
	return u
}

// SetRestored sets the "restored" field.
func (u *SchedulingActionUpsert) SetRestored(v bool) *SchedulingActionUpsert {
	u.Set(schedulingaction.FieldRestored, v)
	return u
}

// UpdateRestored sets the "restored" field to the value that was provided on create.
func (u *SchedulingActionUpsert) UpdateRestored() *SchedulingActionUpsert {
	u.SetExcluded(schedulingaction.FieldRestored)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SchedulingAction.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SchedulingActionUpsertOne) UpdateNewValues() *SchedulingActionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(schedulingaction.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SchedulingAction.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SchedulingActionUpsertOne) Ignore() *SchedulingActionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SchedulingActionUpsertOne) DoNothing() *SchedulingActionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SchedulingActionCreate.OnConflict
// documentation for more info.
func (u *SchedulingActionUpsertOne) Update(set func(*SchedulingActionUpsert)) *SchedulingActionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SchedulingActionUpsert{UpdateSet: update})
	}))
	return u
}

// SetPolicyID sets the "policy_id" field.
func (u *SchedulingActionUpsertOne) SetPolicyID(v int64) *SchedulingActionUpsertOne {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.SetPolicyID(v)
	})
}

// AddPolicyID adds v to the "policy_id" field.
func (u *SchedulingActionUpsertOne) AddPolicyID(v int64) *SchedulingActionUpsertOne {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.AddPolicyID(v)
	})
}

// UpdatePolicyID sets the "policy_id" field to the value that was provided on create.
func (u *SchedulingActionUpsertOne) UpdatePolicyID() *SchedulingActionUpsertOne {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.UpdatePolicyID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *SchedulingActionUpsertOne) SetAccountID(v int64) *SchedulingActionUpsertOne {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *SchedulingActionUpsertOne) AddAccountID(v int64) *SchedulingActionUpsertOne {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *SchedulingActionUpsertOne) UpdateAccountID() *SchedulingActionUpsertOne {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.UpdateAccountID()
	})
}

// SetMonitorID sets the "monitor_id" field.
func (u *SchedulingActionUpsertOne) SetMonitorID(v int64) *SchedulingActionUpsertOne {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.SetMonitorID(v)
	})
}

// AddMonitorID adds v to the "monitor_id" field.
func (u *SchedulingActionUpsertOne) AddMonitorID(v int64) *SchedulingActionUpsertOne {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.AddMonitorID(v)
	})
}

// UpdateMonitorID sets the "monitor_id" field to the value that was provided on create.
func (u *SchedulingActionUpsertOne) UpdateMonitorID() *SchedulingActionUpsertOne {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.UpdateMonitorID()
	})
}

// SetAction sets the "action" field.
func (u *SchedulingActionUpsertOne) SetAction(v string) *SchedulingActionUpsertOne {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *SchedulingActionUpsertOne) UpdateAction() *SchedulingActionUpsertOne {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.UpdateAction()
	})
}

// SetReason sets the "reason" field.
func (u *SchedulingActionUpsertOne) SetReason(v string) *SchedulingActionUpsertOne {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *SchedulingActionUpsertOne) UpdateReason() *SchedulingActionUpsertOne {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.UpdateReason()
	})
}

// SetOriginalPriority sets the "original_priority" field.
func (u *SchedulingActionUpsertOne) SetOriginalPriority(v int) *SchedulingActionUpsertOne {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.SetOriginalPriority(v)
	})
}

// AddOriginalPriority adds v to the "original_priority" field.
func (u *SchedulingActionUpsertOne) AddOriginalPriority(v int) *SchedulingActionUpsertOne {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.AddOriginalPriority(v)
	})
}

// UpdateOriginalPriority sets the "original_priority" field to the value that was provided on create.
func (u *SchedulingActionUpsertOne) UpdateOriginalPriority() *SchedulingActionUpsertOne {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.UpdateOriginalPriority()
	})
}

// SetRestored sets the "restored" field.
func (u *SchedulingActionUpsertOne) SetRestored(v bool) *SchedulingActionUpsertOne {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.SetRestored(v)
	})
}

// UpdateRestored sets the "restored" field to the value that was provided on create.
func (u *SchedulingActionUpsertOne) UpdateRestored() *SchedulingActionUpsertOne {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.UpdateRestored()
	})
}

// Exec executes the query.
func (u *SchedulingActionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SchedulingActionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SchedulingActionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SchedulingActionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SchedulingActionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SchedulingActionCreateBulk is the builder for creating many SchedulingAction entities in bulk.
type SchedulingActionCreateBulk struct {
	config
	err      error
	builders []*SchedulingActionCreate
	conflict []sql.ConflictOption
}

// Save creates the SchedulingAction entities in the database.
func (_c *SchedulingActionCreateBulk) Save(ctx context.Context) ([]*SchedulingAction, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SchedulingAction, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SchedulingActionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SchedulingActionCreateBulk) SaveX(ctx context.Context) []*SchedulingAction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SchedulingActionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SchedulingActionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SchedulingAction.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SchedulingActionUpsert) {
//			SetPolicyID(v+v).
//		}).
//		Exec(ctx)
func (_c *SchedulingActionCreateBulk) OnConflict(opts ...sql.ConflictOption) *SchedulingActionUpsertBulk {
	_c.conflict = opts
	return &SchedulingActionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SchedulingAction.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SchedulingActionCreateBulk) OnConflictColumns(columns ...string) *SchedulingActionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SchedulingActionUpsertBulk{
		create: _c,
	}
}

// SchedulingActionUpsertBulk is the builder for "upsert"-ing
// a bulk of SchedulingAction nodes.
type SchedulingActionUpsertBulk struct {
	create *SchedulingActionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SchedulingAction.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SchedulingActionUpsertBulk) UpdateNewValues() *SchedulingActionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(schedulingaction.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SchedulingAction.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SchedulingActionUpsertBulk) Ignore() *SchedulingActionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SchedulingActionUpsertBulk) DoNothing() *SchedulingActionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SchedulingActionCreateBulk.OnConflict
// documentation for more info.
func (u *SchedulingActionUpsertBulk) Update(set func(*SchedulingActionUpsert)) *SchedulingActionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SchedulingActionUpsert{UpdateSet: update})
	}))
	return u
}

// SetPolicyID sets the "policy_id" field.
func (u *SchedulingActionUpsertBulk) SetPolicyID(v int64) *SchedulingActionUpsertBulk {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.SetPolicyID(v)
	})
}

// AddPolicyID adds v to the "policy_id" field.
func (u *SchedulingActionUpsertBulk) AddPolicyID(v int64) *SchedulingActionUpsertBulk {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.AddPolicyID(v)
	})
}

// UpdatePolicyID sets the "policy_id" field to the value that was provided on create.
func (u *SchedulingActionUpsertBulk) UpdatePolicyID() *SchedulingActionUpsertBulk {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.UpdatePolicyID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *SchedulingActionUpsertBulk) SetAccountID(v int64) *SchedulingActionUpsertBulk {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *SchedulingActionUpsertBulk) AddAccountID(v int64) *SchedulingActionUpsertBulk {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *SchedulingActionUpsertBulk) UpdateAccountID() *SchedulingActionUpsertBulk {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.UpdateAccountID()
	})
}

// SetMonitorID sets the "monitor_id" field.
func (u *SchedulingActionUpsertBulk) SetMonitorID(v int64) *SchedulingActionUpsertBulk {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.SetMonitorID(v)
	})
}

// AddMonitorID adds v to the "monitor_id" field.
func (u *SchedulingActionUpsertBulk) AddMonitorID(v int64) *SchedulingActionUpsertBulk {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.AddMonitorID(v)
	})
}

// UpdateMonitorID sets the "monitor_id" field to the value that was provided on create.
func (u *SchedulingActionUpsertBulk) UpdateMonitorID() *SchedulingActionUpsertBulk {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.UpdateMonitorID()
	})
}

// SetAction sets the "action" field.
func (u *SchedulingActionUpsertBulk) SetAction(v string) *SchedulingActionUpsertBulk {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *SchedulingActionUpsertBulk) UpdateAction() *SchedulingActionUpsertBulk {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.UpdateAction()
	})
}

// SetReason sets the "reason" field.
func (u *SchedulingActionUpsertBulk) SetReason(v string) *SchedulingActionUpsertBulk {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *SchedulingActionUpsertBulk) UpdateReason() *SchedulingActionUpsertBulk {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.UpdateReason()
	})
}

// SetOriginalPriority sets the "original_priority" field.
func (u *SchedulingActionUpsertBulk) SetOriginalPriority(v int) *SchedulingActionUpsertBulk {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.SetOriginalPriority(v)
	})
}

// AddOriginalPriority adds v to the "original_priority" field.
func (u *SchedulingActionUpsertBulk) AddOriginalPriority(v int) *SchedulingActionUpsertBulk {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.AddOriginalPriority(v)
	})
}

// UpdateOriginalPriority sets the "original_priority" field to the value that was provided on create.
func (u *SchedulingActionUpsertBulk) UpdateOriginalPriority() *SchedulingActionUpsertBulk {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.UpdateOriginalPriority()
	})
}

// SetRestored sets the "restored" field.
func (u *SchedulingActionUpsertBulk) SetRestored(v bool) *SchedulingActionUpsertBulk {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.SetRestored(v)
	})
}

// UpdateRestored sets the "restored" field to the value that was provided on create.
func (u *SchedulingActionUpsertBulk) UpdateRestored() *SchedulingActionUpsertBulk {
	return u.Update(func(s *SchedulingActionUpsert) {
		s.UpdateRestored()
	})
}

// Exec executes the query.
func (u *SchedulingActionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SchedulingActionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SchedulingActionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SchedulingActionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
