// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/schedulingpolicy"
)

// SchedulingPolicyUpdate is the builder for updating SchedulingPolicy entities.
type SchedulingPolicyUpdate struct {
	config
	hooks    []Hook
	mutation *SchedulingPolicyMutation
}

// Where appends a list predicates to the SchedulingPolicyUpdate builder.
func (_u *SchedulingPolicyUpdate) Where(ps ...predicate.SchedulingPolicy) *SchedulingPolicyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SchedulingPolicyUpdate) SetUpdatedAt(v time.Time) *SchedulingPolicyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *SchedulingPolicyUpdate) SetName(v string) *SchedulingPolicyUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SchedulingPolicyUpdate) SetNillableName(v *string) *SchedulingPolicyUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *SchedulingPolicyUpdate) SetEnabled(v bool) *SchedulingPolicyUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *SchedulingPolicyUpdate) SetNillableEnabled(v *bool) *SchedulingPolicyUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetMonitorID sets the "monitor_id" field.
func (_u *SchedulingPolicyUpdate) SetMonitorID(v int64) *SchedulingPolicyUpdate {
	_u.mutation.ResetMonitorID()
	_u.mutation.SetMonitorID(v)
	return _u
}

// SetNillableMonitorID sets the "monitor_id" field if the given value is not nil.
func (_u *SchedulingPolicyUpdate) SetNillableMonitorID(v *int64) *SchedulingPolicyUpdate {
	if v != nil {
		_u.SetMonitorID(*v)
	}
	return _u
}

// AddMonitorID adds value to the "monitor_id" field.
func (_u *SchedulingPolicyUpdate) AddMonitorID(v int64) *SchedulingPolicyUpdate {
	_u.mutation.AddMonitorID(v)
	return _u
}

// SetAccountIds sets the "account_ids" field.
func (_u *SchedulingPolicyUpdate) SetAccountIds(v []int64) *SchedulingPolicyUpdate {
	_u.mutation.SetAccountIds(v)
	return _u
}

// AppendAccountIds appends value to the "account_ids" field.
func (_u *SchedulingPolicyUpdate) AppendAccountIds(v []int64) *SchedulingPolicyUpdate {
	_u.mutation.AppendAccountIds(v)
	return _u
}

// SetTriggerConsecutiveFailures sets the "trigger_consecutive_failures" field.
func (_u *SchedulingPolicyUpdate) SetTriggerConsecutiveFailures(v int) *SchedulingPolicyUpdate {
	_u.mutation.ResetTriggerConsecutiveFailures()
	_u.mutation.SetTriggerConsecutiveFailures(v)
	return _u
}

// SetNillableTriggerConsecutiveFailures sets the "trigger_consecutive_failures" field if the given value is not nil.
func (_u *SchedulingPolicyUpdate) SetNillableTriggerConsecutiveFailures(v *int) *SchedulingPolicyUpdate {
	if v != nil {
		_u.SetTriggerConsecutiveFailures(*v)
	}
	return _u
}

// AddTriggerConsecutiveFailures adds value to the "trigger_consecutive_failures" field.
func (_u *SchedulingPolicyUpdate) AddTriggerConsecutiveFailures(v int) *SchedulingPolicyUpdate {
	_u.mutation.AddTriggerConsecutiveFailures(v)
	return _u
}

// SetTriggerLatencyMs sets the "trigger_latency_ms" field.
func (_u *SchedulingPolicyUpdate) SetTriggerLatencyMs(v int) *SchedulingPolicyUpdate {
	_u.mutation.ResetTriggerLatencyMs()
	_u.mutation.SetTriggerLatencyMs(v)
	return _u
}

// SetNillableTriggerLatencyMs sets the "trigger_latency_ms" field if the given value is not nil.
func (_u *SchedulingPolicyUpdate) SetNillableTriggerLatencyMs(v *int) *SchedulingPolicyUpdate {
	if v != nil {
		_u.SetTriggerLatencyMs(*v)
	}
	return _u
}

// AddTriggerLatencyMs adds value to the "trigger_latency_ms" field.
func (_u *SchedulingPolicyUpdate) AddTriggerLatencyMs(v int) *SchedulingPolicyUpdate {
	_u.mutation.AddTriggerLatencyMs(v)
	return _u
}

// SetActionType sets the "action_type" field.
func (_u *SchedulingPolicyUpdate) SetActionType(v string) *SchedulingPolicyUpdate {
	_u.mutation.SetActionType(v)
	return _u
}

// SetNillableActionType sets the "action_type" field if the given value is not nil.
func (_u *SchedulingPolicyUpdate) SetNillableActionType(v *string) *SchedulingPolicyUpdate {
	if v != nil {
		_u.SetActionType(*v)
	}
	return _u
}

// SetPauseMinutes sets the "pause_minutes" field.
func (_u *SchedulingPolicyUpdate) SetPauseMinutes(v int) *SchedulingPolicyUpdate {
	_u.mutation.ResetPauseMinutes()
	_u.mutation.SetPauseMinutes(v)
	return _u
}

// SetNillablePauseMinutes sets the "pause_minutes" field if the given value is not nil.
func (_u *SchedulingPolicyUpdate) SetNillablePauseMinutes(v *int) *SchedulingPolicyUpdate {
	if v != nil {
		_u.SetPauseMinutes(*v)
	}
	return _u
}

// AddPauseMinutes adds value to the "pause_minutes" field.
func (_u *SchedulingPolicyUpdate) AddPauseMinutes(v int) *SchedulingPolicyUpdate {
	_u.mutation.AddPauseMinutes(v)
	return _u
}

// SetPriorityDelta sets the "priority_delta" field.
func (_u *SchedulingPolicyUpdate) SetPriorityDelta(v int) *SchedulingPolicyUpdate {
	_u.mutation.ResetPriorityDelta()
	_u.mutation.SetPriorityDelta(v)
	return _u
}

// SetNillablePriorityDelta sets the "priority_delta" field if the given value is not nil.
func (_u *SchedulingPolicyUpdate) SetNillablePriorityDelta(v *int) *SchedulingPolicyUpdate {
	if v != nil {
		_u.SetPriorityDelta(*v)
	}
	return _u
}

// AddPriorityDelta adds value to the "priority_delta" field.
func (_u *SchedulingPolicyUpdate) AddPriorityDelta(v int) *SchedulingPolicyUpdate {
	_u.mutation.AddPriorityDelta(v)
	return _u
}

// SetRecoverConsecutiveSuccesses sets the "recover_consecutive_successes" field.
func (_u *SchedulingPolicyUpdate) SetRecoverConsecutiveSuccesses(v int) *SchedulingPolicyUpdate {
	_u.mutation.ResetRecoverConsecutiveSuccesses()
	_u.mutation.SetRecoverConsecutiveSuccesses(v)
	return _u
}

// SetNillableRecoverConsecutiveSuccesses sets the "recover_consecutive_successes" field if the given value is not nil.
func (_u *SchedulingPolicyUpdate) SetNillableRecoverConsecutiveSuccesses(v *int) *SchedulingPolicyUpdate {
	if v != nil {
		_u.SetRecoverConsecutiveSuccesses(*v)
	}
	return _u
}

// AddRecoverConsecutiveSuccesses adds value to the "recover_consecutive_successes" field.
func (_u *SchedulingPolicyUpdate) AddRecoverConsecutiveSuccesses(v int) *SchedulingPolicyUpdate {
	_u.mutation.AddRecoverConsecutiveSuccesses(v)
	return _u
}

// SetCooldownMinutes sets the "cooldown_minutes" field.
func (_u *SchedulingPolicyUpdate) SetCooldownMinutes(v int) *SchedulingPolicyUpdate {
	_u.mutation.ResetCooldownMinutes()
	_u.mutation.SetCooldownMinutes(v)
	return _u
}

// SetNillableCooldownMinutes sets the "cooldown_minutes" field if the given value is not nil.
func (_u *SchedulingPolicyUpdate) SetNillableCooldownMinutes(v *int) *SchedulingPolicyUpdate {
	if v != nil {
		_u.SetCooldownMinutes(*v)
	}
	return _u
}

// AddCooldownMinutes adds value to the "cooldown_minutes" field.
func (_u *SchedulingPolicyUpdate) AddCooldownMinutes(v int) *SchedulingPolicyUpdate {
	_u.mutation.AddCooldownMinutes(v)
	return _u
}

// Mutation returns the SchedulingPolicyMutation object of the builder.
func (_u *SchedulingPolicyUpdate) Mutation() *SchedulingPolicyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SchedulingPolicyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SchedulingPolicyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SchedulingPolicyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SchedulingPolicyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SchedulingPolicyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := schedulingpolicy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SchedulingPolicyUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := schedulingpolicy.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SchedulingPolicy.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TriggerConsecutiveFailures(); ok {
		if err := schedulingpolicy.TriggerConsecutiveFailuresValidator(v); err != nil {
			return &ValidationError{Name: "trigger_consecutive_failures", err: fmt.Errorf(`ent: validator failed for field "SchedulingPolicy.trigger_consecutive_failures": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TriggerLatencyMs(); ok {
		if err := schedulingpolicy.TriggerLatencyMsValidator(v); err != nil {
			return &ValidationError{Name: "trigger_latency_ms", err: fmt.Errorf(`ent: validator failed for field "SchedulingPolicy.trigger_latency_ms": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActionType(); ok {
		if err := schedulingpolicy.ActionTypeValidator(v); err != nil {
			return &ValidationError{Name: "action_type", err: fmt.Errorf(`ent: validator failed for field "SchedulingPolicy.action_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PauseMinutes(); ok {
		if err := schedulingpolicy.PauseMinutesValidator(v); err != nil {
			return &ValidationError{Name: "pause_minutes", err: fmt.Errorf(`ent: validator failed for field "SchedulingPolicy.pause_minutes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PriorityDelta(); ok {
		if err := schedulingpolicy.PriorityDeltaValidator(v); err != nil {
			return &ValidationError{Name: "priority_delta", err: fmt.Errorf(`ent: validator failed for field "SchedulingPolicy.priority_delta": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RecoverConsecutiveSuccesses(); ok {
		if err := schedulingpolicy.RecoverConsecutiveSuccessesValidator(v); err != nil {
			return &ValidationError{Name: "recover_consecutive_successes", err: fmt.Errorf(`ent: validator failed for field "SchedulingPolicy.recover_consecutive_successes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CooldownMinutes(); ok {
		if err := schedulingpolicy.CooldownMinutesValidator(v); err != nil {
			return &ValidationError{Name: "cooldown_minutes", err: fmt.Errorf(`ent: validator failed for field "SchedulingPolicy.cooldown_minutes": %w`, err)}
		}
	}
	return nil
}

func (_u *SchedulingPolicyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(schedulingpolicy.Table, schedulingpolicy.Columns, sqlgraph.NewFieldSpec(schedulingpolicy.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(schedulingpolicy.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(schedulingpolicy.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(schedulingpolicy.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MonitorID(); ok {
		_spec.SetField(schedulingpolicy.FieldMonitorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMonitorID(); ok {
		_spec.AddField(schedulingpolicy.FieldMonitorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AccountIds(); ok {
		_spec.SetField(schedulingpolicy.FieldAccountIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAccountIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, schedulingpolicy.FieldAccountIds, value)
		})
	}
	if value, ok := _u.mutation.TriggerConsecutiveFailures(); ok {
		_spec.SetField(schedulingpolicy.FieldTriggerConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTriggerConsecutiveFailures(); ok {
		_spec.AddField(schedulingpolicy.FieldTriggerConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TriggerLatencyMs(); ok {
		_spec.SetField(schedulingpolicy.FieldTriggerLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTriggerLatencyMs(); ok {
		_spec.AddField(schedulingpolicy.FieldTriggerLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ActionType(); ok {
		_spec.SetField(schedulingpolicy.FieldActionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PauseMinutes(); ok {
		_spec.SetField(schedulingpolicy.FieldPauseMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPauseMinutes(); ok {
		_spec.AddField(schedulingpolicy.FieldPauseMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PriorityDelta(); ok {
		_spec.SetField(schedulingpolicy.FieldPriorityDelta, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriorityDelta(); ok {
		_spec.AddField(schedulingpolicy.FieldPriorityDelta, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RecoverConsecutiveSuccesses(); ok {
		_spec.SetField(schedulingpolicy.FieldRecoverConsecutiveSuccesses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRecoverConsecutiveSuccesses(); ok {
		_spec.AddField(schedulingpolicy.FieldRecoverConsecutiveSuccesses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CooldownMinutes(); ok {
		_spec.SetField(schedulingpolicy.FieldCooldownMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCooldownMinutes(); ok {
		_spec.AddField(schedulingpolicy.FieldCooldownMinutes, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schedulingpolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SchedulingPolicyUpdateOne is the builder for updating a single SchedulingPolicy entity.
type SchedulingPolicyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SchedulingPolicyMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SchedulingPolicyUpdateOne) SetUpdatedAt(v time.Time) *SchedulingPolicyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *SchedulingPolicyUpdateOne) SetName(v string) *SchedulingPolicyUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SchedulingPolicyUpdateOne) SetNillableName(v *string) *SchedulingPolicyUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *SchedulingPolicyUpdateOne) SetEnabled(v bool) *SchedulingPolicyUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *SchedulingPolicyUpdateOne) SetNillableEnabled(v *bool) *SchedulingPolicyUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetMonitorID sets the "monitor_id" field.
func (_u *SchedulingPolicyUpdateOne) SetMonitorID(v int64) *SchedulingPolicyUpdateOne {
	_u.mutation.ResetMonitorID()
	_u.mutation.SetMonitorID(v)
	return _u
}

// SetNillableMonitorID sets the "monitor_id" field if the given value is not nil.
func (_u *SchedulingPolicyUpdateOne) SetNillableMonitorID(v *int64) *SchedulingPolicyUpdateOne {
	if v != nil {
		_u.SetMonitorID(*v)
	}
	return _u
}

// AddMonitorID adds value to the "monitor_id" field.
func (_u *SchedulingPolicyUpdateOne) AddMonitorID(v int64) *SchedulingPolicyUpdateOne {
	_u.mutation.AddMonitorID(v)
	return _u
}

// SetAccountIds sets the "account_ids" field.
func (_u *SchedulingPolicyUpdateOne) SetAccountIds(v []int64) *SchedulingPolicyUpdateOne {
	_u.mutation.SetAccountIds(v)
	return _u
}

// AppendAccountIds appends value to the "account_ids" field.
func (_u *SchedulingPolicyUpdateOne) AppendAccountIds(v []int64) *SchedulingPolicyUpdateOne {
	_u.mutation.AppendAccountIds(v)
	return _u
}

// SetTriggerConsecutiveFailures sets the "trigger_consecutive_failures" field.
func (_u *SchedulingPolicyUpdateOne) SetTriggerConsecutiveFailures(v int) *SchedulingPolicyUpdateOne {
	_u.mutation.ResetTriggerConsecutiveFailures()
	_u.mutation.SetTriggerConsecutiveFailures(v)
	return _u
}

// SetNillableTriggerConsecutiveFailures sets the "trigger_consecutive_failures" field if the given value is not nil.
func (_u *SchedulingPolicyUpdateOne) SetNillableTriggerConsecutiveFailures(v *int) *SchedulingPolicyUpdateOne {
	if v != nil {
		_u.SetTriggerConsecutiveFailures(*v)
	}
	return _u
}

// AddTriggerConsecutiveFailures adds value to the "trigger_consecutive_failures" field.
func (_u *SchedulingPolicyUpdateOne) AddTriggerConsecutiveFailures(v int) *SchedulingPolicyUpdateOne {
	_u.mutation.AddTriggerConsecutiveFailures(v)
	return _u
}

// SetTriggerLatencyMs sets the "trigger_latency_ms" field.
func (_u *SchedulingPolicyUpdateOne) SetTriggerLatencyMs(v int) *SchedulingPolicyUpdateOne {
	_u.mutation.ResetTriggerLatencyMs()
	_u.mutation.SetTriggerLatencyMs(v)
	return _u
}

// SetNillableTriggerLatencyMs sets the "trigger_latency_ms" field if the given value is not nil.
func (_u *SchedulingPolicyUpdateOne) SetNillableTriggerLatencyMs(v *int) *SchedulingPolicyUpdateOne {
	if v != nil {
		_u.SetTriggerLatencyMs(*v)
	}
	return _u
}

// AddTriggerLatencyMs adds value to the "trigger_latency_ms" field.
func (_u *SchedulingPolicyUpdateOne) AddTriggerLatencyMs(v int) *SchedulingPolicyUpdateOne {
	_u.mutation.AddTriggerLatencyMs(v)
	return _u
}

// SetActionType sets the "action_type" field.
func (_u *SchedulingPolicyUpdateOne) SetActionType(v string) *SchedulingPolicyUpdateOne {
	_u.mutation.SetActionType(v)
	return _u
}

// SetNillableActionType sets the "action_type" field if the given value is not nil.
func (_u *SchedulingPolicyUpdateOne) SetNillableActionType(v *string) *SchedulingPolicyUpdateOne {
	if v != nil {
		_u.SetActionType(*v)
	}
	return _u
}

// SetPauseMinutes sets the "pause_minutes" field.
func (_u *SchedulingPolicyUpdateOne) SetPauseMinutes(v int) *SchedulingPolicyUpdateOne {
	_u.mutation.ResetPauseMinutes()
	_u.mutation.SetPauseMinutes(v)
	return _u
}

// SetNillablePauseMinutes sets the "pause_minutes" field if the given value is not nil.
func (_u *SchedulingPolicyUpdateOne) SetNillablePauseMinutes(v *int) *SchedulingPolicyUpdateOne {
	if v != nil {
		_u.SetPauseMinutes(*v)
	}
	return _u
}

// AddPauseMinutes adds value to the "pause_minutes" field.
func (_u *SchedulingPolicyUpdateOne) AddPauseMinutes(v int) *SchedulingPolicyUpdateOne {
	_u.mutation.AddPauseMinutes(v)
	return _u
}

// SetPriorityDelta sets the "priority_delta" field.
func (_u *SchedulingPolicyUpdateOne) SetPriorityDelta(v int) *SchedulingPolicyUpdateOne {
	_u.mutation.ResetPriorityDelta()
	_u.mutation.SetPriorityDelta(v)
	return _u
}

// SetNillablePriorityDelta sets the "priority_delta" field if the given value is not nil.
func (_u *SchedulingPolicyUpdateOne) SetNillablePriorityDelta(v *int) *SchedulingPolicyUpdateOne {
	if v != nil {
		_u.SetPriorityDelta(*v)
	}
	return _u
}

// AddPriorityDelta adds value to the "priority_delta" field.
func (_u *SchedulingPolicyUpdateOne) AddPriorityDelta(v int) *SchedulingPolicyUpdateOne {
	_u.mutation.AddPriorityDelta(v)
	return _u
}

// SetRecoverConsecutiveSuccesses sets the "recover_consecutive_successes" field.
func (_u *SchedulingPolicyUpdateOne) SetRecoverConsecutiveSuccesses(v int) *SchedulingPolicyUpdateOne {
	_u.mutation.ResetRecoverConsecutiveSuccesses()
	_u.mutation.SetRecoverConsecutiveSuccesses(v)
	return _u
}

// SetNillableRecoverConsecutiveSuccesses sets the "recover_consecutive_successes" field if the given value is not nil.
func (_u *SchedulingPolicyUpdateOne) SetNillableRecoverConsecutiveSuccesses(v *int) *SchedulingPolicyUpdateOne {
	if v != nil {
		_u.SetRecoverConsecutiveSuccesses(*v)
	}
	return _u
}

// AddRecoverConsecutiveSuccesses adds value to the "recover_consecutive_successes" field.
func (_u *SchedulingPolicyUpdateOne) AddRecoverConsecutiveSuccesses(v int) *SchedulingPolicyUpdateOne {
	_u.mutation.AddRecoverConsecutiveSuccesses(v)
	return _u
}

// SetCooldownMinutes sets the "cooldown_minutes" field.
func (_u *SchedulingPolicyUpdateOne) SetCooldownMinutes(v int) *SchedulingPolicyUpdateOne {
	_u.mutation.ResetCooldownMinutes()
	_u.mutation.SetCooldownMinutes(v)
	return _u
}

// SetNillableCooldownMinutes sets the "cooldown_minutes" field if the given value is not nil.
func (_u *SchedulingPolicyUpdateOne) SetNillableCooldownMinutes(v *int) *SchedulingPolicyUpdateOne {
	if v != nil {
		_u.SetCooldownMinutes(*v)
	}
	return _u
}

// AddCooldownMinutes adds value to the "cooldown_minutes" field.
func (_u *SchedulingPolicyUpdateOne) AddCooldownMinutes(v int) *SchedulingPolicyUpdateOne {
	_u.mutation.AddCooldownMinutes(v)
	return _u
}

// Mutation returns the SchedulingPolicyMutation object of the builder.
func (_u *SchedulingPolicyUpdateOne) Mutation() *SchedulingPolicyMutation {
	return _u.mutation
}

// Where appends a list predicates to the SchedulingPolicyUpdate builder.
func (_u *SchedulingPolicyUpdateOne) Where(ps ...predicate.SchedulingPolicy) *SchedulingPolicyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SchedulingPolicyUpdateOne) Select(field string, fields ...string) *SchedulingPolicyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SchedulingPolicy entity.
func (_u *SchedulingPolicyUpdateOne) Save(ctx context.Context) (*SchedulingPolicy, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SchedulingPolicyUpdateOne) SaveX(ctx context.Context) *SchedulingPolicy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SchedulingPolicyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SchedulingPolicyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SchedulingPolicyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := schedulingpolicy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SchedulingPolicyUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := schedulingpolicy.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SchedulingPolicy.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TriggerConsecutiveFailures(); ok {
		if err := schedulingpolicy.TriggerConsecutiveFailuresValidator(v); err != nil {
			return &ValidationError{Name: "trigger_consecutive_failures", err: fmt.Errorf(`ent: validator failed for field "SchedulingPolicy.trigger_consecutive_failures": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TriggerLatencyMs(); ok {
		if err := schedulingpolicy.TriggerLatencyMsValidator(v); err != nil {
			return &ValidationError{Name: "trigger_latency_ms", err: fmt.Errorf(`ent: validator failed for field "SchedulingPolicy.trigger_latency_ms": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActionType(); ok {
		if err := schedulingpolicy.ActionTypeValidator(v); err != nil {
			return &ValidationError{Name: "action_type", err: fmt.Errorf(`ent: validator failed for field "SchedulingPolicy.action_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PauseMinutes(); ok {
		if err := schedulingpolicy.PauseMinutesValidator(v); err != nil {
			return &ValidationError{Name: "pause_minutes", err: fmt.Errorf(`ent: validator failed for field "SchedulingPolicy.pause_minutes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PriorityDelta(); ok {
		if err := schedulingpolicy.PriorityDeltaValidator(v); err != nil {
			return &ValidationError{Name: "priority_delta", err: fmt.Errorf(`ent: validator failed for field "SchedulingPolicy.priority_delta": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RecoverConsecutiveSuccesses(); ok {
		if err := schedulingpolicy.RecoverConsecutiveSuccessesValidator(v); err != nil {
			return &ValidationError{Name: "recover_consecutive_successes", err: fmt.Errorf(`ent: validator failed for field "SchedulingPolicy.recover_consecutive_successes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CooldownMinutes(); ok {
		if err := schedulingpolicy.CooldownMinutesValidator(v); err != nil {
			return &ValidationError{Name: "cooldown_minutes", err: fmt.Errorf(`ent: validator failed for field "SchedulingPolicy.cooldown_minutes": %w`, err)}
		}
	}
	return nil
}

func (_u *SchedulingPolicyUpdateOne) sqlSave(ctx context.Context) (_node *SchedulingPolicy, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(schedulingpolicy.Table, schedulingpolicy.Columns, sqlgraph.NewFieldSpec(schedulingpolicy.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SchedulingPolicy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, schedulingpolicy.FieldID)
		for _, f := range fields {
			if !schedulingpolicy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != schedulingpolicy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(schedulingpolicy.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(schedulingpolicy.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(schedulingpolicy.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MonitorID(); ok {
		_spec.SetField(schedulingpolicy.FieldMonitorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMonitorID(); ok {
		_spec.AddField(schedulingpolicy.FieldMonitorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AccountIds(); ok {
		_spec.SetField(schedulingpolicy.FieldAccountIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAccountIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, schedulingpolicy.FieldAccountIds, value)
		})
	}
	if value, ok := _u.mutation.TriggerConsecutiveFailures(); ok {
		_spec.SetField(schedulingpolicy.FieldTriggerConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTriggerConsecutiveFailures(); ok {
		_spec.AddField(schedulingpolicy.FieldTriggerConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TriggerLatencyMs(); ok {
		_spec.SetField(schedulingpolicy.FieldTriggerLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTriggerLatencyMs(); ok {
		_spec.AddField(schedulingpolicy.FieldTriggerLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ActionType(); ok {
		_spec.SetField(schedulingpolicy.FieldActionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PauseMinutes(); ok {
		_spec.SetField(schedulingpolicy.FieldPauseMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPauseMinutes(); ok {
		_spec.AddField(schedulingpolicy.FieldPauseMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PriorityDelta(); ok {
		_spec.SetField(schedulingpolicy.FieldPriorityDelta, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriorityDelta(); ok {
		_spec.AddField(schedulingpolicy.FieldPriorityDelta, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RecoverConsecutiveSuccesses(); ok {
		_spec.SetField(schedulingpolicy.FieldRecoverConsecutiveSuccesses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRecoverConsecutiveSuccesses(); ok {
		_spec.AddField(schedulingpolicy.FieldRecoverConsecutiveSuccesses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CooldownMinutes(); ok {
		_spec.SetField(schedulingpolicy.FieldCooldownMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCooldownMinutes(); ok {
		_spec.AddField(schedulingpolicy.FieldCooldownMinutes, field.TypeInt, value)
	}
	_node = &SchedulingPolicy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schedulingpolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
