// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/schedulingaction"
)

// SchedulingActionUpdate is the builder for updating SchedulingAction entities.
type SchedulingActionUpdate struct {
	config
	hooks    []Hook
	mutation *SchedulingActionMutation
}

// Where appends a list predicates to the SchedulingActionUpdate builder.
func (_u *SchedulingActionUpdate) Where(ps ...predicate.SchedulingAction) *SchedulingActionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPolicyID sets the "policy_id" field.
func (_u *SchedulingActionUpdate) SetPolicyID(v int64) *SchedulingActionUpdate {
	_u.mutation.ResetPolicyID()
	_u.mutation.SetPolicyID(v)
	return _u
}

// SetNillablePolicyID sets the "policy_id" field if the given value is not nil.
func (_u *SchedulingActionUpdate) SetNillablePolicyID(v *int64) *SchedulingActionUpdate {
	if v != nil {
		_u.SetPolicyID(*v)
	}
	return _u
}

// AddPolicyID adds value to the "policy_id" field.
func (_u *SchedulingActionUpdate) AddPolicyID(v int64) *SchedulingActionUpdate {
	_u.mutation.AddPolicyID(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *SchedulingActionUpdate) SetAccountID(v int64) *SchedulingActionUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *SchedulingActionUpdate) SetNillableAccountID(v *int64) *SchedulingActionUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *SchedulingActionUpdate) AddAccountID(v int64) *SchedulingActionUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetMonitorID sets the "monitor_id" field.
func (_u *SchedulingActionUpdate) SetMonitorID(v int64) *SchedulingActionUpdate {
	_u.mutation.ResetMonitorID()
	_u.mutation.SetMonitorID(v)
	return _u
}

// SetNillableMonitorID sets the "monitor_id" field if the given value is not nil.
func (_u *SchedulingActionUpdate) SetNillableMonitorID(v *int64) *SchedulingActionUpdate {
	if v != nil {
		_u.SetMonitorID(*v)
	}
	return _u
}

// AddMonitorID adds value to the "monitor_id" field.
func (_u *SchedulingActionUpdate) AddMonitorID(v int64) *SchedulingActionUpdate {
	_u.mutation.AddMonitorID(v)
	return _u
}

// SetAction sets the "action" field.
func (_u *SchedulingActionUpdate) SetAction(v string) *SchedulingActionUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *SchedulingActionUpdate) SetNillableAction(v *string) *SchedulingActionUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *SchedulingActionUpdate) SetReason(v string) *SchedulingActionUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *SchedulingActionUpdate) SetNillableReason(v *string) *SchedulingActionUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetOriginalPriority sets the "original_priority" field.
func (_u *SchedulingActionUpdate) SetOriginalPriority(v int) *SchedulingActionUpdate {
	_u.mutation.ResetOriginalPriority()
	_u.mutation.SetOriginalPriority(v)
	return _u
}

// SetNillableOriginalPriority sets the "original_priority" field if the given value is not nil.
func (_u *SchedulingActionUpdate) SetNillableOriginalPriority(v *int) *SchedulingActionUpdate {
	if v != nil {
		_u.SetOriginalPriority(*v)
	}
	return _u
}

// AddOriginalPriority adds value to the "original_priority" field.
func (_u *SchedulingActionUpdate) AddOriginalPriority(v int) *SchedulingActionUpdate {
	_u.mutation.AddOriginalPriority(v)
	return _u
}

// SetRestored sets the "restored" field.
func (_u *SchedulingActionUpdate) SetRestored(v bool) *SchedulingActionUpdate {
	_u.mutation.SetRestored(v)
	return _u
}

// SetNillableRestored sets the "restored" field if the given value is not nil.
func (_u *SchedulingActionUpdate) SetNillableRestored(v *bool) *SchedulingActionUpdate {
	if v != nil {
		_u.SetRestored(*v)
	}
	return _u
}

// Mutation returns the SchedulingActionMutation object of the builder.
func (_u *SchedulingActionUpdate) Mutation() *SchedulingActionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SchedulingActionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SchedulingActionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SchedulingActionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SchedulingActionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SchedulingActionUpdate) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := schedulingaction.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "SchedulingAction.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Reason(); ok {
		if err := schedulingaction.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "SchedulingAction.reason": %w`, err)}
		}
	}
	return nil
}

func (_u *SchedulingActionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(schedulingaction.Table, schedulingaction.Columns, sqlgraph.NewFieldSpec(schedulingaction.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PolicyID(); ok {
		_spec.SetField(schedulingaction.FieldPolicyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPolicyID(); ok {
		_spec.AddField(schedulingaction.FieldPolicyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(schedulingaction.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(schedulingaction.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MonitorID(); ok {
		_spec.SetField(schedulingaction.FieldMonitorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMonitorID(); ok {
		_spec.AddField(schedulingaction.FieldMonitorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(schedulingaction.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(schedulingaction.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginalPriority(); ok {
		_spec.SetField(schedulingaction.FieldOriginalPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOriginalPriority(); ok {
		_spec.AddField(schedulingaction.FieldOriginalPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Restored(); ok {
		_spec.SetField(schedulingaction.FieldRestored, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schedulingaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SchedulingActionUpdateOne is the builder for updating a single SchedulingAction entity.
type SchedulingActionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SchedulingActionMutation
}

// SetPolicyID sets the "policy_id" field.
func (_u *SchedulingActionUpdateOne) SetPolicyID(v int64) *SchedulingActionUpdateOne {
	_u.mutation.ResetPolicyID()
	_u.mutation.SetPolicyID(v)
	return _u
}

// SetNillablePolicyID sets the "policy_id" field if the given value is not nil.
func (_u *SchedulingActionUpdateOne) SetNillablePolicyID(v *int64) *SchedulingActionUpdateOne {
	if v != nil {
		_u.SetPolicyID(*v)
	}
	return _u
}

// AddPolicyID adds value to the "policy_id" field.
func (_u *SchedulingActionUpdateOne) AddPolicyID(v int64) *SchedulingActionUpdateOne {
	_u.mutation.AddPolicyID(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *SchedulingActionUpdateOne) SetAccountID(v int64) *SchedulingActionUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *SchedulingActionUpdateOne) SetNillableAccountID(v *int64) *SchedulingActionUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *SchedulingActionUpdateOne) AddAccountID(v int64) *SchedulingActionUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetMonitorID sets the "monitor_id" field.
func (_u *SchedulingActionUpdateOne) SetMonitorID(v int64) *SchedulingActionUpdateOne {
	_u.mutation.ResetMonitorID()
	_u.mutation.SetMonitorID(v)
	return _u
}

// SetNillableMonitorID sets the "monitor_id" field if the given value is not nil.
func (_u *SchedulingActionUpdateOne) SetNillableMonitorID(v *int64) *SchedulingActionUpdateOne {
	if v != nil {
		_u.SetMonitorID(*v)
	}
	return _u
}

// AddMonitorID adds value to the "monitor_id" field.
func (_u *SchedulingActionUpdateOne) AddMonitorID(v int64) *SchedulingActionUpdateOne {
	_u.mutation.AddMonitorID(v)
	return _u
}

// SetAction sets the "action" field.
func (_u *SchedulingActionUpdateOne) SetAction(v string) *SchedulingActionUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *SchedulingActionUpdateOne) SetNillableAction(v *string) *SchedulingActionUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *SchedulingActionUpdateOne) SetReason(v string) *SchedulingActionUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *SchedulingActionUpdateOne) SetNillableReason(v *string) *SchedulingActionUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetOriginalPriority sets the "original_priority" field.
func (_u *SchedulingActionUpdateOne) SetOriginalPriority(v int) *SchedulingActionUpdateOne {
	_u.mutation.ResetOriginalPriority()
	_u.mutation.SetOriginalPriority(v)
	return _u
}

// SetNillableOriginalPriority sets the "original_priority" field if the given value is not nil.
func (_u *SchedulingActionUpdateOne) SetNillableOriginalPriority(v *int) *SchedulingActionUpdateOne {
	if v != nil {
		_u.SetOriginalPriority(*v)
	}
	return _u
}

// AddOriginalPriority adds value to the "original_priority" field.
func (_u *SchedulingActionUpdateOne) AddOriginalPriority(v int) *SchedulingActionUpdateOne {
	_u.mutation.AddOriginalPriority(v)
	return _u
}

// SetRestored sets the "restored" field.
func (_u *SchedulingActionUpdateOne) SetRestored(v bool) *SchedulingActionUpdateOne {
	_u.mutation.SetRestored(v)
	return _u
}

// SetNillableRestored sets the "restored" field if the given value is not nil.
func (_u *SchedulingActionUpdateOne) SetNillableRestored(v *bool) *SchedulingActionUpdateOne {
	if v != nil {
		_u.SetRestored(*v)
	}
	return _u
}

// Mutation returns the SchedulingActionMutation object of the builder.
func (_u *SchedulingActionUpdateOne) Mutation() *SchedulingActionMutation {
	return _u.mutation
}

// Where appends a list predicates to the SchedulingActionUpdate builder.
func (_u *SchedulingActionUpdateOne) Where(ps ...predicate.SchedulingAction) *SchedulingActionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SchedulingActionUpdateOne) Select(field string, fields ...string) *SchedulingActionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SchedulingAction entity.
func (_u *SchedulingActionUpdateOne) Save(ctx context.Context) (*SchedulingAction, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SchedulingActionUpdateOne) SaveX(ctx context.Context) *SchedulingAction {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SchedulingActionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SchedulingActionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SchedulingActionUpdateOne) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := schedulingaction.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "SchedulingAction.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Reason(); ok {
		if err := schedulingaction.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "SchedulingAction.reason": %w`, err)}
		}
	}
	return nil
}

func (_u *SchedulingActionUpdateOne) sqlSave(ctx context.Context) (_node *SchedulingAction, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(schedulingaction.Table, schedulingaction.Columns, sqlgraph.NewFieldSpec(schedulingaction.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SchedulingAction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, schedulingaction.FieldID)
		for _, f := range fields {
			if !schedulingaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != schedulingaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PolicyID(); ok {
		_spec.SetField(schedulingaction.FieldPolicyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPolicyID(); ok {
		_spec.AddField(schedulingaction.FieldPolicyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(schedulingaction.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(schedulingaction.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MonitorID(); ok {
		_spec.SetField(schedulingaction.FieldMonitorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMonitorID(); ok {
		_spec.AddField(schedulingaction.FieldMonitorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(schedulingaction.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(schedulingaction.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginalPriority(); ok {
		_spec.SetField(schedulingaction.FieldOriginalPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOriginalPriority(); ok {
		_spec.AddField(schedulingaction.FieldOriginalPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Restored(); ok {
		_spec.SetField(schedulingaction.FieldRestored, field.TypeBool, value)
	}
	_node = &SchedulingAction{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schedulingaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
